# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GTEMSwitch.ui'
#
# Created: Fri Sep 24 10:30:52 2010
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_GTEMRelaisController(object):
    def setupUi(self, GTEMRelaisController):
        GTEMRelaisController.setObjectName("GTEMRelaisController")
        GTEMRelaisController.resize(772, 409)
        self.centralwidget = QtGui.QWidget(GTEMRelaisController)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 200, 111, 141))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 91, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sgSwitch_LF = QtGui.QRadioButton(self.layoutWidget)
        self.sgSwitch_LF.setEnabled(True)
        self.sgSwitch_LF.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.sgSwitch_LF.setChecked(False)
        self.sgSwitch_LF.setObjectName("sgSwitch_LF")
        self.verticalLayout.addWidget(self.sgSwitch_LF)
        self.sgSwitch_HF = QtGui.QRadioButton(self.layoutWidget)
        self.sgSwitch_HF.setEnabled(True)
        self.sgSwitch_HF.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.sgSwitch_HF.setObjectName("sgSwitch_HF")
        self.verticalLayout.addWidget(self.sgSwitch_HF)
        self.sgSwitch_Direct = QtGui.QRadioButton(self.layoutWidget)
        self.sgSwitch_Direct.setEnabled(True)
        self.sgSwitch_Direct.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.sgSwitch_Direct.setChecked(True)
        self.sgSwitch_Direct.setObjectName("sgSwitch_Direct")
        self.verticalLayout.addWidget(self.sgSwitch_Direct)
        self.conn_amp_lf = QtGui.QFrame(self.centralwidget)
        self.conn_amp_lf.setEnabled(False)
        self.conn_amp_lf.setGeometry(QtCore.QRect(170, 230, 231, 16))
        self.conn_amp_lf.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_lf.setLineWidth(2)
        self.conn_amp_lf.setFrameShape(QtGui.QFrame.HLine)
#        self.conn_amp_lf.setFrameShadow(QtGui.QFrame.Sunken)
        self.conn_amp_lf.setObjectName("conn_amp_lf")
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(190, 209, 61, 41))
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 0, 61, 41))
        self.groupBox_4.setAutoFillBackground(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_5.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_5.setAutoFillBackground(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.conn_amp_hf = QtGui.QFrame(self.centralwidget)
        self.conn_amp_hf.setEnabled(False)
        self.conn_amp_hf.setGeometry(QtCore.QRect(170, 270, 231, 16))
        self.conn_amp_hf.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_hf.setLineWidth(2)
        self.conn_amp_hf.setFrameShape(QtGui.QFrame.HLine)
#        self.conn_amp_hf.setFrameShadow(QtGui.QFrame.Sunken)
        self.conn_amp_hf.setObjectName("conn_amp_hf")
        self.conn_amp_direct = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct.setGeometry(QtCore.QRect(170, 300, 231, 16))
        self.conn_amp_direct.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct.setLineWidth(2)
        self.conn_amp_direct.setFrameShape(QtGui.QFrame.HLine)
#        self.conn_amp_direct.setFrameShadow(QtGui.QFrame.Sunken)
        self.conn_amp_direct.setObjectName("conn_amp_direct")
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(190, 250, 61, 41))
        self.groupBox_3.setAutoFillBackground(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(400, 220, 31, 101))
        self.frame.setStyleSheet("color: black;")
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.conn_amp_direct_2 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_2.setGeometry(QtCore.QRect(430, 270, 31, 16))
        self.conn_amp_direct_2.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_2.setLineWidth(2)
        self.conn_amp_direct_2.setFrameShape(QtGui.QFrame.HLine)
#        self.conn_amp_direct_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.conn_amp_direct_2.setObjectName("conn_amp_direct_2")
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(270, 210, 41, 41))
        self.groupBox_6.setAutoFillBackground(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_7.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_7.setAutoFillBackground(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.groupBox_8 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(330, 250, 41, 41))
        self.groupBox_8.setAutoFillBackground(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox_9.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_9.setAutoFillBackground(True)
        self.groupBox_9.setObjectName("groupBox_9")
        self.groupBox_10 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_10.setGeometry(QtCore.QRect(460, 200, 81, 141))
        self.groupBox_10.setFlat(False)
        self.groupBox_10.setCheckable(False)
        self.groupBox_10.setObjectName("groupBox_10")
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox_10)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 61, 111))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TxSwitch_GTEM = QtGui.QRadioButton(self.layoutWidget_2)
        self.TxSwitch_GTEM.setEnabled(True)
        self.TxSwitch_GTEM.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.TxSwitch_GTEM.setChecked(False)
        self.TxSwitch_GTEM.setObjectName("TxSwitch_GTEM")
        self.verticalLayout_2.addWidget(self.TxSwitch_GTEM)
        self.TxSwitch_Term = QtGui.QRadioButton(self.layoutWidget_2)
        self.TxSwitch_Term.setEnabled(True)
        self.TxSwitch_Term.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.TxSwitch_Term.setChecked(True)
        self.TxSwitch_Term.setObjectName("TxSwitch_Term")
        self.verticalLayout_2.addWidget(self.TxSwitch_Term)
        self.conn_amp_direct_3 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_3.setEnabled(False)
        self.conn_amp_direct_3.setGeometry(QtCore.QRect(540, 240, 101, 16))
        self.conn_amp_direct_3.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_3.setLineWidth(2)
        self.conn_amp_direct_3.setFrameShape(QtGui.QFrame.HLine)
#        self.conn_amp_direct_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.conn_amp_direct_3.setObjectName("conn_amp_direct_3")
        self.conn_amp_direct_5 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_5.setGeometry(QtCore.QRect(540, 290, 31, 16))
        self.conn_amp_direct_5.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_5.setLineWidth(2)
        self.conn_amp_direct_5.setFrameShape(QtGui.QFrame.HLine)
#        self.conn_amp_direct_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.conn_amp_direct_5.setObjectName("conn_amp_direct_5")
        self.groupBox_11 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_11.setGeometry(QtCore.QRect(700, 250, 61, 31))
        self.groupBox_11.setAutoFillBackground(True)
        self.groupBox_11.setObjectName("groupBox_11")
        self.groupBox_12 = QtGui.QGroupBox(self.groupBox_11)
        self.groupBox_12.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_12.setAutoFillBackground(True)
        self.groupBox_12.setObjectName("groupBox_12")
        self.groupBox_25 = QtGui.QGroupBox(self.groupBox_11)
        self.groupBox_25.setGeometry(QtCore.QRect(0, 40, 61, 31))
        self.groupBox_25.setAutoFillBackground(True)
        self.groupBox_25.setObjectName("groupBox_25")
        self.groupBox_15 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_15.setGeometry(QtCore.QRect(560, 280, 41, 31))
        self.groupBox_15.setAutoFillBackground(True)
        self.groupBox_15.setObjectName("groupBox_15")
        self.groupBox_17 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_17.setGeometry(QtCore.QRect(10, 247, 31, 31))
        self.groupBox_17.setFlat(False)
        self.groupBox_17.setCheckable(False)
        self.groupBox_17.setObjectName("groupBox_17")
        self.conn_amp_direct_6 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_6.setGeometry(QtCore.QRect(40, 260, 21, 20))
        self.conn_amp_direct_6.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_6.setLineWidth(2)
        self.conn_amp_direct_6.setFrameShape(QtGui.QFrame.HLine)
#        self.conn_amp_direct_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.conn_amp_direct_6.setObjectName("conn_amp_direct_6")
        self.groupBox_18 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_18.setGeometry(QtCore.QRect(10, 66, 61, 31))
        self.groupBox_18.setFlat(False)
        self.groupBox_18.setCheckable(False)
        self.groupBox_18.setObjectName("groupBox_18")
        self.groupBox_19 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_19.setGeometry(QtCore.QRect(10, 107, 61, 31))
        self.groupBox_19.setFlat(False)
        self.groupBox_19.setCheckable(False)
        self.groupBox_19.setObjectName("groupBox_19")
        self.conn_amp_direct_7 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_7.setEnabled(False)
        self.conn_amp_direct_7.setGeometry(QtCore.QRect(70, 120, 31, 16))
        self.conn_amp_direct_7.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_7.setLineWidth(2)
        self.conn_amp_direct_7.setFrameShape(QtGui.QFrame.HLine)
#        self.conn_amp_direct_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.conn_amp_direct_7.setObjectName("conn_amp_direct_7")
        self.conn_amp_direct_8 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_8.setEnabled(False)
        self.conn_amp_direct_8.setGeometry(QtCore.QRect(70, 80, 31, 16))
        self.conn_amp_direct_8.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_8.setLineWidth(2)
        self.conn_amp_direct_8.setFrameShape(QtGui.QFrame.HLine)
#        self.conn_amp_direct_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.conn_amp_direct_8.setObjectName("conn_amp_direct_8")
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(100, 70, 31, 71))
        self.frame_2.setStyleSheet("color: black;")
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.conn_amp_direct_9 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_9.setEnabled(False)
        self.conn_amp_direct_9.setGeometry(QtCore.QRect(130, 70, 151, 16))
        self.conn_amp_direct_9.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_9.setLineWidth(2)
        self.conn_amp_direct_9.setFrameShape(QtGui.QFrame.HLine)
#        self.conn_amp_direct_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.conn_amp_direct_9.setObjectName("conn_amp_direct_9")
        self.conn_amp_direct_10 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_10.setEnabled(False)
        self.conn_amp_direct_10.setGeometry(QtCore.QRect(130, 80, 211, 16))
        self.conn_amp_direct_10.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_10.setLineWidth(2)
        self.conn_amp_direct_10.setFrameShape(QtGui.QFrame.HLine)
#        self.conn_amp_direct_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.conn_amp_direct_10.setObjectName("conn_amp_direct_10")
        self.conn_amp_direct_11 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_11.setEnabled(False)
        self.conn_amp_direct_11.setGeometry(QtCore.QRect(130, 110, 171, 16))
        self.conn_amp_direct_11.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_11.setLineWidth(2)
        self.conn_amp_direct_11.setFrameShape(QtGui.QFrame.HLine)
#        self.conn_amp_direct_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.conn_amp_direct_11.setObjectName("conn_amp_direct_11")
        self.conn_amp_direct_12 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_12.setEnabled(False)
        self.conn_amp_direct_12.setGeometry(QtCore.QRect(130, 120, 230, 16))
        self.conn_amp_direct_12.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_12.setLineWidth(2)
        self.conn_amp_direct_12.setFrameShape(QtGui.QFrame.HLine)
#        self.conn_amp_direct_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.conn_amp_direct_12.setObjectName("conn_amp_direct_12")
        self.conn_amp_direct_13 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_13.setEnabled(False)
        self.conn_amp_direct_13.setGeometry(QtCore.QRect(270, 77, 20, 150))
        self.conn_amp_direct_13.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_13.setLineWidth(2)
        self.conn_amp_direct_13.setFrameShape(QtGui.QFrame.VLine)
#        self.conn_amp_direct_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.conn_amp_direct_13.setObjectName("conn_amp_direct_13")
        self.conn_amp_direct_14 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_14.setEnabled(False)
        self.conn_amp_direct_14.setGeometry(QtCore.QRect(330, 88, 20, 180))
        self.conn_amp_direct_14.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_14.setLineWidth(2)
        self.conn_amp_direct_14.setFrameShape(QtGui.QFrame.VLine)
#        self.conn_amp_direct_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.conn_amp_direct_14.setObjectName("conn_amp_direct_14")
        self.conn_amp_direct_15 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_15.setEnabled(False)
        self.conn_amp_direct_15.setGeometry(QtCore.QRect(290, 118, 20, 110))
        self.conn_amp_direct_15.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_15.setLineWidth(2)
        self.conn_amp_direct_15.setFrameShape(QtGui.QFrame.VLine)
#        self.conn_amp_direct_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.conn_amp_direct_15.setObjectName("conn_amp_direct_15")
        self.conn_amp_direct_16 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_16.setEnabled(False)
        self.conn_amp_direct_16.setGeometry(QtCore.QRect(350, 128, 20, 140))
        self.conn_amp_direct_16.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_16.setLineWidth(2)
        self.conn_amp_direct_16.setFrameShape(QtGui.QFrame.VLine)
#        self.conn_amp_direct_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.conn_amp_direct_16.setObjectName("conn_amp_direct_16")
        self.conn_amp_direct_23 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_23.setEnabled(True)
        self.conn_amp_direct_23.setGeometry(QtCore.QRect(60, 370, 561, 20))
        self.conn_amp_direct_23.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_23.setLineWidth(2)
        self.conn_amp_direct_23.setFrameShape(QtGui.QFrame.HLine)
#        self.conn_amp_direct_23.setFrameShadow(QtGui.QFrame.Sunken)
        self.conn_amp_direct_23.setObjectName("conn_amp_direct_23")
        self.groupBox_35 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_35.setGeometry(QtCore.QRect(10, 360, 51, 31))
        self.groupBox_35.setFlat(False)
        self.groupBox_35.setCheckable(False)
        self.groupBox_35.setObjectName("groupBox_35")
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(440, 70, 161, 71))
        self.pushButton.setObjectName("pushButton")
        self.conn_amp_direct_17 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_17.setGeometry(QtCore.QRect(670, 260, 31, 16))
        self.conn_amp_direct_17.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_17.setLineWidth(2)
        self.conn_amp_direct_17.setFrameShape(QtGui.QFrame.HLine)
#        self.conn_amp_direct_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.conn_amp_direct_17.setObjectName("conn_amp_direct_17")
        self.conn_amp_direct_18 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_18.setEnabled(True)
        self.conn_amp_direct_18.setGeometry(QtCore.QRect(610, 300, 20, 81))
        self.conn_amp_direct_18.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_18.setLineWidth(2)
        self.conn_amp_direct_18.setFrameShape(QtGui.QFrame.VLine)
#        self.conn_amp_direct_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.conn_amp_direct_18.setObjectName("conn_amp_direct_18")
        self.conn_amp_direct_19 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_19.setEnabled(True)
        self.conn_amp_direct_19.setGeometry(QtCore.QRect(620, 290, 21, 20))
        self.conn_amp_direct_19.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_19.setLineWidth(2)
        self.conn_amp_direct_19.setFrameShape(QtGui.QFrame.HLine)
#        self.conn_amp_direct_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.conn_amp_direct_19.setObjectName("conn_amp_direct_19")
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(640, 220, 31, 101))
        self.frame_3.setStyleSheet("color: black;")
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        GTEMRelaisController.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(GTEMRelaisController)
        self.statusbar.setObjectName("statusbar")
        GTEMRelaisController.setStatusBar(self.statusbar)

        self.retranslateUi(GTEMRelaisController)
        QtCore.QObject.connect(self.sgSwitch_Direct, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct.setEnabled)
        QtCore.QObject.connect(self.sgSwitch_HF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_hf.setEnabled)
        QtCore.QObject.connect(self.sgSwitch_LF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_lf.setEnabled)
        QtCore.QObject.connect(self.sgSwitch_HF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_14.setEnabled)
        QtCore.QObject.connect(self.sgSwitch_HF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_16.setEnabled)
        QtCore.QObject.connect(self.sgSwitch_LF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_13.setEnabled)
        QtCore.QObject.connect(self.sgSwitch_LF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_15.setEnabled)
        QtCore.QObject.connect(self.sgSwitch_LF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_11.setEnabled)
        QtCore.QObject.connect(self.sgSwitch_LF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_9.setEnabled)
        QtCore.QObject.connect(self.sgSwitch_HF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_10.setEnabled)
        QtCore.QObject.connect(self.sgSwitch_HF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_12.setEnabled)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), self.sgSwitch_Direct.click)
        QtCore.QObject.connect(self.sgSwitch_Direct, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_7.setDisabled)
        QtCore.QObject.connect(self.sgSwitch_Direct, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_8.setDisabled)
        QtCore.QObject.connect(self.sgSwitch_HF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_7.setEnabled)
        QtCore.QObject.connect(self.sgSwitch_HF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_8.setEnabled)
        QtCore.QObject.connect(self.sgSwitch_LF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_7.setEnabled)
        QtCore.QObject.connect(self.sgSwitch_LF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_8.setEnabled)
        QtCore.QObject.connect(self.TxSwitch_Term, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_5.setEnabled)
        QtCore.QObject.connect(self.TxSwitch_GTEM, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_3.setEnabled)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), self.TxSwitch_Term.click)
        QtCore.QObject.connect(self.TxSwitch_Term, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_19.setEnabled)
        QtCore.QObject.connect(self.TxSwitch_Term, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_18.setEnabled)
        QtCore.QObject.connect(self.TxSwitch_Term, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_23.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(GTEMRelaisController)

    def retranslateUi(self, GTEMRelaisController):
        GTEMRelaisController.setWindowTitle(QtGui.QApplication.translate("GTEMRelaisController", "GTEM Matrix Switch Controller ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("GTEMRelaisController", "Switch 1", None, QtGui.QApplication.UnicodeUTF8))
        self.sgSwitch_LF.setText(QtGui.QApplication.translate("GTEMRelaisController", "LF", None, QtGui.QApplication.UnicodeUTF8))
        self.sgSwitch_HF.setText(QtGui.QApplication.translate("GTEMRelaisController", "HF", None, QtGui.QApplication.UnicodeUTF8))
        self.sgSwitch_Direct.setText(QtGui.QApplication.translate("GTEMRelaisController", "Direct", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("GTEMRelaisController", "Amp LF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("GTEMRelaisController", "Amp LF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("GTEMRelaisController", "Amp LF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("GTEMRelaisController", "Amp HF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("GTEMRelaisController", "DC LF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("GTEMRelaisController", "Amp LF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("GTEMRelaisController", "DC HF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("GTEMRelaisController", "Amp LF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("GTEMRelaisController", "Switch 2", None, QtGui.QApplication.UnicodeUTF8))
        self.TxSwitch_GTEM.setText(QtGui.QApplication.translate("GTEMRelaisController", "GTEM", None, QtGui.QApplication.UnicodeUTF8))
        self.TxSwitch_Term.setText(QtGui.QApplication.translate("GTEMRelaisController", "Term", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_11.setTitle(QtGui.QApplication.translate("GTEMRelaisController", "GTEM", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_12.setTitle(QtGui.QApplication.translate("GTEMRelaisController", "Amp LF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_25.setTitle(QtGui.QApplication.translate("GTEMRelaisController", "Horn", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_15.setTitle(QtGui.QApplication.translate("GTEMRelaisController", "Term", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_17.setTitle(QtGui.QApplication.translate("GTEMRelaisController", "SG", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_18.setTitle(QtGui.QApplication.translate("GTEMRelaisController", "PM FWD", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_19.setTitle(QtGui.QApplication.translate("GTEMRelaisController", "PM REV", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_35.setTitle(QtGui.QApplication.translate("GTEMRelaisController", "Rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("GTEMRelaisController", "Safe Setting", None, QtGui.QApplication.UnicodeUTF8))

