# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'GTEMSwitch.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGroupBox, QMainWindow,
    QPushButton, QRadioButton, QSizePolicy, QStatusBar,
    QVBoxLayout, QWidget)

class Ui_GTEMRelaisController(object):
    def setupUi(self, GTEMRelaisController):
        if not GTEMRelaisController.objectName():
            GTEMRelaisController.setObjectName(u"GTEMRelaisController")
        GTEMRelaisController.resize(721, 476)
        GTEMRelaisController.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.centralwidget = QWidget(GTEMRelaisController)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(60, 200, 111, 141))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.layoutWidget = QWidget(self.groupBox)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 20, 91, 111))
        self.verticalLayout = QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.sgSwitch_LF = QRadioButton(self.layoutWidget)
        self.sgSwitch_LF.setObjectName(u"sgSwitch_LF")
        self.sgSwitch_LF.setEnabled(True)
        self.sgSwitch_LF.setLayoutDirection(Qt.RightToLeft)
        self.sgSwitch_LF.setChecked(False)

        self.verticalLayout.addWidget(self.sgSwitch_LF)

        self.sgSwitch_HF = QRadioButton(self.layoutWidget)
        self.sgSwitch_HF.setObjectName(u"sgSwitch_HF")
        self.sgSwitch_HF.setEnabled(True)
        self.sgSwitch_HF.setLayoutDirection(Qt.RightToLeft)

        self.verticalLayout.addWidget(self.sgSwitch_HF)

        self.sgSwitch_Direct = QRadioButton(self.layoutWidget)
        self.sgSwitch_Direct.setObjectName(u"sgSwitch_Direct")
        self.sgSwitch_Direct.setEnabled(True)
        self.sgSwitch_Direct.setLayoutDirection(Qt.RightToLeft)
        self.sgSwitch_Direct.setChecked(True)

        self.verticalLayout.addWidget(self.sgSwitch_Direct)

        self.conn_amp_lf = QFrame(self.centralwidget)
        self.conn_amp_lf.setObjectName(u"conn_amp_lf")
        self.conn_amp_lf.setEnabled(False)
        self.conn_amp_lf.setGeometry(QRect(170, 230, 231, 16))
        self.conn_amp_lf.setFrameShadow(QFrame.Plain)
        self.conn_amp_lf.setLineWidth(2)
        self.conn_amp_lf.setFrameShape(QFrame.Shape.HLine)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(190, 209, 61, 41))
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_4 = QGroupBox(self.groupBox_2)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(0, 0, 61, 41))
        self.groupBox_4.setAutoFillBackground(True)
        self.groupBox_5 = QGroupBox(self.groupBox_4)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(30, 40, 61, 41))
        self.groupBox_5.setAutoFillBackground(True)
        self.conn_amp_hf = QFrame(self.centralwidget)
        self.conn_amp_hf.setObjectName(u"conn_amp_hf")
        self.conn_amp_hf.setEnabled(False)
        self.conn_amp_hf.setGeometry(QRect(170, 270, 231, 16))
        self.conn_amp_hf.setFrameShadow(QFrame.Plain)
        self.conn_amp_hf.setLineWidth(2)
        self.conn_amp_hf.setFrameShape(QFrame.Shape.HLine)
        self.conn_amp_direct = QFrame(self.centralwidget)
        self.conn_amp_direct.setObjectName(u"conn_amp_direct")
        self.conn_amp_direct.setGeometry(QRect(170, 300, 231, 16))
        self.conn_amp_direct.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct.setLineWidth(2)
        self.conn_amp_direct.setFrameShape(QFrame.Shape.HLine)
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(190, 250, 61, 41))
        self.groupBox_3.setAutoFillBackground(True)
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(400, 220, 31, 101))
        self.frame.setStyleSheet(u"color: black;")
        self.frame.setFrameShape(QFrame.Box)
        self.frame.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_2 = QFrame(self.centralwidget)
        self.conn_amp_direct_2.setObjectName(u"conn_amp_direct_2")
        self.conn_amp_direct_2.setGeometry(QRect(430, 270, 31, 16))
        self.conn_amp_direct_2.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_2.setLineWidth(2)
        self.conn_amp_direct_2.setFrameShape(QFrame.Shape.HLine)
        self.groupBox_6 = QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(270, 210, 41, 41))
        self.groupBox_6.setAutoFillBackground(True)
        self.groupBox_7 = QGroupBox(self.groupBox_6)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(30, 40, 61, 41))
        self.groupBox_7.setAutoFillBackground(True)
        self.groupBox_8 = QGroupBox(self.centralwidget)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(330, 250, 41, 41))
        self.groupBox_8.setAutoFillBackground(True)
        self.groupBox_9 = QGroupBox(self.groupBox_8)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(30, 40, 61, 41))
        self.groupBox_9.setAutoFillBackground(True)
        self.groupBox_10 = QGroupBox(self.centralwidget)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(460, 210, 81, 120))
        self.groupBox_10.setFlat(False)
        self.groupBox_10.setCheckable(False)
        self.layoutWidget_2 = QWidget(self.groupBox_10)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(10, 20, 61, 91))
        self.verticalLayout_2 = QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.TxSwitch_Term = QRadioButton(self.layoutWidget_2)
        self.TxSwitch_Term.setObjectName(u"TxSwitch_Term")
        self.TxSwitch_Term.setEnabled(True)
        self.TxSwitch_Term.setLayoutDirection(Qt.RightToLeft)
        self.TxSwitch_Term.setChecked(True)

        self.verticalLayout_2.addWidget(self.TxSwitch_Term)

        self.TxSwitch_GTEM = QRadioButton(self.layoutWidget_2)
        self.TxSwitch_GTEM.setObjectName(u"TxSwitch_GTEM")
        self.TxSwitch_GTEM.setEnabled(True)
        self.TxSwitch_GTEM.setLayoutDirection(Qt.RightToLeft)
        self.TxSwitch_GTEM.setChecked(False)

        self.verticalLayout_2.addWidget(self.TxSwitch_GTEM)

        self.conn_amp_direct_3 = QFrame(self.centralwidget)
        self.conn_amp_direct_3.setObjectName(u"conn_amp_direct_3")
        self.conn_amp_direct_3.setEnabled(False)
        self.conn_amp_direct_3.setGeometry(QRect(540, 290, 31, 16))
        self.conn_amp_direct_3.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_3.setLineWidth(2)
        self.conn_amp_direct_3.setFrameShape(QFrame.Shape.HLine)
        self.groupBox_11 = QGroupBox(self.centralwidget)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(630, 310, 61, 31))
        self.groupBox_11.setAutoFillBackground(True)
        self.groupBox_12 = QGroupBox(self.groupBox_11)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(30, 40, 61, 41))
        self.groupBox_12.setAutoFillBackground(True)
        self.groupBox_25 = QGroupBox(self.groupBox_11)
        self.groupBox_25.setObjectName(u"groupBox_25")
        self.groupBox_25.setGeometry(QRect(0, 40, 61, 31))
        self.groupBox_25.setAutoFillBackground(True)
        self.groupBox_15 = QGroupBox(self.centralwidget)
        self.groupBox_15.setObjectName(u"groupBox_15")
        self.groupBox_15.setGeometry(QRect(640, 230, 41, 31))
        self.groupBox_15.setAutoFillBackground(True)
        self.groupBox_17 = QGroupBox(self.centralwidget)
        self.groupBox_17.setObjectName(u"groupBox_17")
        self.groupBox_17.setGeometry(QRect(10, 247, 31, 31))
        self.groupBox_17.setFlat(False)
        self.groupBox_17.setCheckable(False)
        self.conn_amp_direct_6 = QFrame(self.centralwidget)
        self.conn_amp_direct_6.setObjectName(u"conn_amp_direct_6")
        self.conn_amp_direct_6.setGeometry(QRect(40, 260, 21, 20))
        self.conn_amp_direct_6.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_6.setLineWidth(2)
        self.conn_amp_direct_6.setFrameShape(QFrame.Shape.HLine)
        self.groupBox_18 = QGroupBox(self.centralwidget)
        self.groupBox_18.setObjectName(u"groupBox_18")
        self.groupBox_18.setGeometry(QRect(10, 66, 61, 31))
        self.groupBox_18.setFlat(False)
        self.groupBox_18.setCheckable(False)
        self.groupBox_19 = QGroupBox(self.centralwidget)
        self.groupBox_19.setObjectName(u"groupBox_19")
        self.groupBox_19.setGeometry(QRect(10, 107, 61, 31))
        self.groupBox_19.setFlat(False)
        self.groupBox_19.setCheckable(False)
        self.conn_amp_direct_7 = QFrame(self.centralwidget)
        self.conn_amp_direct_7.setObjectName(u"conn_amp_direct_7")
        self.conn_amp_direct_7.setEnabled(False)
        self.conn_amp_direct_7.setGeometry(QRect(70, 120, 31, 16))
        self.conn_amp_direct_7.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_7.setLineWidth(2)
        self.conn_amp_direct_7.setFrameShape(QFrame.Shape.HLine)
        self.conn_amp_direct_8 = QFrame(self.centralwidget)
        self.conn_amp_direct_8.setObjectName(u"conn_amp_direct_8")
        self.conn_amp_direct_8.setEnabled(False)
        self.conn_amp_direct_8.setGeometry(QRect(70, 80, 31, 16))
        self.conn_amp_direct_8.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_8.setLineWidth(2)
        self.conn_amp_direct_8.setFrameShape(QFrame.Shape.HLine)
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(100, 70, 31, 71))
        self.frame_2.setStyleSheet(u"color: black;")
        self.frame_2.setFrameShape(QFrame.Box)
        self.frame_2.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_9 = QFrame(self.centralwidget)
        self.conn_amp_direct_9.setObjectName(u"conn_amp_direct_9")
        self.conn_amp_direct_9.setEnabled(False)
        self.conn_amp_direct_9.setGeometry(QRect(130, 70, 151, 16))
        self.conn_amp_direct_9.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_9.setLineWidth(2)
        self.conn_amp_direct_9.setFrameShape(QFrame.Shape.HLine)
        self.conn_amp_direct_10 = QFrame(self.centralwidget)
        self.conn_amp_direct_10.setObjectName(u"conn_amp_direct_10")
        self.conn_amp_direct_10.setEnabled(False)
        self.conn_amp_direct_10.setGeometry(QRect(130, 80, 211, 16))
        self.conn_amp_direct_10.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_10.setLineWidth(2)
        self.conn_amp_direct_10.setFrameShape(QFrame.Shape.HLine)
        self.conn_amp_direct_11 = QFrame(self.centralwidget)
        self.conn_amp_direct_11.setObjectName(u"conn_amp_direct_11")
        self.conn_amp_direct_11.setEnabled(False)
        self.conn_amp_direct_11.setGeometry(QRect(130, 110, 171, 16))
        self.conn_amp_direct_11.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_11.setLineWidth(2)
        self.conn_amp_direct_11.setFrameShape(QFrame.Shape.HLine)
        self.conn_amp_direct_12 = QFrame(self.centralwidget)
        self.conn_amp_direct_12.setObjectName(u"conn_amp_direct_12")
        self.conn_amp_direct_12.setEnabled(False)
        self.conn_amp_direct_12.setGeometry(QRect(130, 120, 230, 16))
        self.conn_amp_direct_12.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_12.setLineWidth(2)
        self.conn_amp_direct_12.setFrameShape(QFrame.Shape.HLine)
        self.conn_amp_direct_13 = QFrame(self.centralwidget)
        self.conn_amp_direct_13.setObjectName(u"conn_amp_direct_13")
        self.conn_amp_direct_13.setEnabled(False)
        self.conn_amp_direct_13.setGeometry(QRect(270, 77, 20, 150))
        self.conn_amp_direct_13.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_13.setLineWidth(2)
        self.conn_amp_direct_13.setFrameShape(QFrame.Shape.VLine)
        self.conn_amp_direct_14 = QFrame(self.centralwidget)
        self.conn_amp_direct_14.setObjectName(u"conn_amp_direct_14")
        self.conn_amp_direct_14.setEnabled(False)
        self.conn_amp_direct_14.setGeometry(QRect(330, 88, 20, 180))
        self.conn_amp_direct_14.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_14.setLineWidth(2)
        self.conn_amp_direct_14.setFrameShape(QFrame.Shape.VLine)
        self.conn_amp_direct_15 = QFrame(self.centralwidget)
        self.conn_amp_direct_15.setObjectName(u"conn_amp_direct_15")
        self.conn_amp_direct_15.setEnabled(False)
        self.conn_amp_direct_15.setGeometry(QRect(290, 118, 20, 110))
        self.conn_amp_direct_15.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_15.setLineWidth(2)
        self.conn_amp_direct_15.setFrameShape(QFrame.Shape.VLine)
        self.conn_amp_direct_16 = QFrame(self.centralwidget)
        self.conn_amp_direct_16.setObjectName(u"conn_amp_direct_16")
        self.conn_amp_direct_16.setEnabled(False)
        self.conn_amp_direct_16.setGeometry(QRect(350, 128, 20, 140))
        self.conn_amp_direct_16.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_16.setLineWidth(2)
        self.conn_amp_direct_16.setFrameShape(QFrame.Shape.VLine)
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(440, 70, 161, 71))
        self.conn_amp_direct_17 = QFrame(self.centralwidget)
        self.conn_amp_direct_17.setObjectName(u"conn_amp_direct_17")
        self.conn_amp_direct_17.setGeometry(QRect(600, 320, 31, 16))
        self.conn_amp_direct_17.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_17.setLineWidth(2)
        self.conn_amp_direct_17.setFrameShape(QFrame.Shape.HLine)
        self.conn_amp_direct_19 = QFrame(self.centralwidget)
        self.conn_amp_direct_19.setObjectName(u"conn_amp_direct_19")
        self.conn_amp_direct_19.setEnabled(False)
        self.conn_amp_direct_19.setGeometry(QRect(540, 350, 31, 20))
        self.conn_amp_direct_19.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_19.setLineWidth(2)
        self.conn_amp_direct_19.setFrameShape(QFrame.Shape.HLine)
        self.frame_3 = QFrame(self.centralwidget)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(570, 280, 31, 101))
        self.frame_3.setStyleSheet(u"color: black;")
        self.frame_3.setFrameShape(QFrame.Box)
        self.frame_3.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_5 = QFrame(self.centralwidget)
        self.conn_amp_direct_5.setObjectName(u"conn_amp_direct_5")
        self.conn_amp_direct_5.setGeometry(QRect(540, 240, 101, 16))
        self.conn_amp_direct_5.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_5.setLineWidth(2)
        self.conn_amp_direct_5.setFrameShape(QFrame.Shape.HLine)
        self.groupBox_13 = QGroupBox(self.centralwidget)
        self.groupBox_13.setObjectName(u"groupBox_13")
        self.groupBox_13.setGeometry(QRect(460, 330, 81, 120))
        self.groupBox_13.setFlat(False)
        self.groupBox_13.setCheckable(False)
        self.layoutWidget_3 = QWidget(self.groupBox_13)
        self.layoutWidget_3.setObjectName(u"layoutWidget_3")
        self.layoutWidget_3.setGeometry(QRect(10, 20, 61, 91))
        self.verticalLayout_3 = QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.RxSwitch_GTEM = QRadioButton(self.layoutWidget_3)
        self.RxSwitch_GTEM.setObjectName(u"RxSwitch_GTEM")
        self.RxSwitch_GTEM.setEnabled(True)
        self.RxSwitch_GTEM.setLayoutDirection(Qt.RightToLeft)
        self.RxSwitch_GTEM.setChecked(False)

        self.verticalLayout_3.addWidget(self.RxSwitch_GTEM)

        self.RxSwitch_Term = QRadioButton(self.layoutWidget_3)
        self.RxSwitch_Term.setObjectName(u"RxSwitch_Term")
        self.RxSwitch_Term.setEnabled(True)
        self.RxSwitch_Term.setLayoutDirection(Qt.RightToLeft)
        self.RxSwitch_Term.setChecked(True)

        self.verticalLayout_3.addWidget(self.RxSwitch_Term)

        self.groupBox_16 = QGroupBox(self.centralwidget)
        self.groupBox_16.setObjectName(u"groupBox_16")
        self.groupBox_16.setGeometry(QRect(640, 400, 41, 31))
        self.groupBox_16.setAutoFillBackground(True)
        self.conn_amp_direct_18 = QFrame(self.centralwidget)
        self.conn_amp_direct_18.setObjectName(u"conn_amp_direct_18")
        self.conn_amp_direct_18.setGeometry(QRect(540, 410, 101, 16))
        self.conn_amp_direct_18.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_18.setLineWidth(2)
        self.conn_amp_direct_18.setFrameShape(QFrame.Shape.HLine)
        self.groupBox_14 = QGroupBox(self.centralwidget)
        self.groupBox_14.setObjectName(u"groupBox_14")
        self.groupBox_14.setGeometry(QRect(10, 340, 81, 91))
        self.groupBox_14.setFlat(False)
        self.groupBox_14.setCheckable(False)
        self.layoutWidget_4 = QWidget(self.groupBox_14)
        self.layoutWidget_4.setObjectName(u"layoutWidget_4")
        self.layoutWidget_4.setGeometry(QRect(10, 20, 62, 61))
        self.verticalLayout_4 = QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.RxSwitch_30M = QRadioButton(self.layoutWidget_4)
        self.RxSwitch_30M.setObjectName(u"RxSwitch_30M")
        self.RxSwitch_30M.setEnabled(True)
        self.RxSwitch_30M.setLayoutDirection(Qt.RightToLeft)
        self.RxSwitch_30M.setChecked(True)

        self.verticalLayout_4.addWidget(self.RxSwitch_30M)

        self.RxSwitch_3G = QRadioButton(self.layoutWidget_4)
        self.RxSwitch_3G.setObjectName(u"RxSwitch_3G")
        self.RxSwitch_3G.setEnabled(True)
        self.RxSwitch_3G.setLayoutDirection(Qt.RightToLeft)
        self.RxSwitch_3G.setChecked(False)

        self.verticalLayout_4.addWidget(self.RxSwitch_3G)

        self.conn_amp_direct_20 = QFrame(self.centralwidget)
        self.conn_amp_direct_20.setObjectName(u"conn_amp_direct_20")
        self.conn_amp_direct_20.setEnabled(True)
        self.conn_amp_direct_20.setGeometry(QRect(90, 380, 371, 20))
        self.conn_amp_direct_20.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_20.setLineWidth(2)
        self.conn_amp_direct_20.setFrameShape(QFrame.Shape.HLine)
        GTEMRelaisController.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(GTEMRelaisController)
        self.statusbar.setObjectName(u"statusbar")
        GTEMRelaisController.setStatusBar(self.statusbar)

        self.retranslateUi(GTEMRelaisController)
        self.sgSwitch_Direct.toggled.connect(self.conn_amp_direct.setEnabled)
        self.sgSwitch_HF.toggled.connect(self.conn_amp_hf.setEnabled)
        self.sgSwitch_LF.toggled.connect(self.conn_amp_lf.setEnabled)
        self.sgSwitch_HF.toggled.connect(self.conn_amp_direct_14.setEnabled)
        self.sgSwitch_HF.toggled.connect(self.conn_amp_direct_16.setEnabled)
        self.sgSwitch_LF.toggled.connect(self.conn_amp_direct_13.setEnabled)
        self.sgSwitch_LF.toggled.connect(self.conn_amp_direct_15.setEnabled)
        self.sgSwitch_LF.toggled.connect(self.conn_amp_direct_11.setEnabled)
        self.sgSwitch_LF.toggled.connect(self.conn_amp_direct_9.setEnabled)
        self.sgSwitch_HF.toggled.connect(self.conn_amp_direct_10.setEnabled)
        self.sgSwitch_HF.toggled.connect(self.conn_amp_direct_12.setEnabled)
        self.pushButton.clicked.connect(self.sgSwitch_Direct.click)
        self.sgSwitch_Direct.toggled.connect(self.conn_amp_direct_7.setDisabled)
        self.sgSwitch_Direct.toggled.connect(self.conn_amp_direct_8.setDisabled)
        self.sgSwitch_HF.toggled.connect(self.conn_amp_direct_7.setEnabled)
        self.sgSwitch_HF.toggled.connect(self.conn_amp_direct_8.setEnabled)
        self.sgSwitch_LF.toggled.connect(self.conn_amp_direct_7.setEnabled)
        self.sgSwitch_LF.toggled.connect(self.conn_amp_direct_8.setEnabled)
        self.TxSwitch_Term.toggled.connect(self.conn_amp_direct_5.setEnabled)
        self.TxSwitch_GTEM.toggled.connect(self.conn_amp_direct_3.setEnabled)
        self.pushButton.clicked.connect(self.TxSwitch_Term.click)
        self.pushButton.clicked.connect(self.RxSwitch_Term.click)
        self.pushButton.clicked.connect(self.RxSwitch_30M.click)
        self.RxSwitch_GTEM.toggled.connect(self.conn_amp_direct_19.setEnabled)

        QMetaObject.connectSlotsByName(GTEMRelaisController)
    # setupUi

    def retranslateUi(self, GTEMRelaisController):
        GTEMRelaisController.setWindowTitle(QCoreApplication.translate("GTEMRelaisController", u"GTEM Matrix Switch Controller ", None))
        self.groupBox.setTitle(QCoreApplication.translate("GTEMRelaisController", u"Switch 1", None))
        self.sgSwitch_LF.setText(QCoreApplication.translate("GTEMRelaisController", u"LF", None))
        self.sgSwitch_HF.setText(QCoreApplication.translate("GTEMRelaisController", u"HF", None))
        self.sgSwitch_Direct.setText(QCoreApplication.translate("GTEMRelaisController", u"Direct", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("GTEMRelaisController", u"Amp LF", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("GTEMRelaisController", u"Amp LF", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("GTEMRelaisController", u"Amp LF", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("GTEMRelaisController", u"Amp HF", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("GTEMRelaisController", u"DC LF", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("GTEMRelaisController", u"Amp LF", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("GTEMRelaisController", u"DC HF", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("GTEMRelaisController", u"Amp LF", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("GTEMRelaisController", u"Switch 2", None))
        self.TxSwitch_Term.setText(QCoreApplication.translate("GTEMRelaisController", u"Term", None))
        self.TxSwitch_GTEM.setText(QCoreApplication.translate("GTEMRelaisController", u"GTEM", None))
        self.groupBox_11.setTitle(QCoreApplication.translate("GTEMRelaisController", u"GTEM", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("GTEMRelaisController", u"Amp LF", None))
        self.groupBox_25.setTitle(QCoreApplication.translate("GTEMRelaisController", u"Horn", None))
        self.groupBox_15.setTitle(QCoreApplication.translate("GTEMRelaisController", u"Term", None))
        self.groupBox_17.setTitle(QCoreApplication.translate("GTEMRelaisController", u"SG", None))
        self.groupBox_18.setTitle(QCoreApplication.translate("GTEMRelaisController", u"PM FWD", None))
        self.groupBox_19.setTitle(QCoreApplication.translate("GTEMRelaisController", u"PM REV", None))
        self.pushButton.setText(QCoreApplication.translate("GTEMRelaisController", u"Safe Setting", None))
        self.groupBox_13.setTitle(QCoreApplication.translate("GTEMRelaisController", u"Switch 3", None))
        self.RxSwitch_GTEM.setText(QCoreApplication.translate("GTEMRelaisController", u"GTEM", None))
        self.RxSwitch_Term.setText(QCoreApplication.translate("GTEMRelaisController", u"Term", None))
        self.groupBox_16.setTitle(QCoreApplication.translate("GTEMRelaisController", u"Term", None))
        self.groupBox_14.setTitle(QCoreApplication.translate("GTEMRelaisController", u"Rec", None))
        self.RxSwitch_30M.setText(QCoreApplication.translate("GTEMRelaisController", u"30M", None))
        self.RxSwitch_3G.setText(QCoreApplication.translate("GTEMRelaisController", u"3G", None))
    # retranslateUi

