# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GTEMSwitch.ui'
#
# Created: Wed Sep 29 11:26:02 2010
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!


from PyQt5.QtWidgets import *
from PyQt5 import QtCore
from PyQt5.QtCore import *


class Ui_GTEMRelaisController(object):
    def setupUi(self, GTEMRelaisController):
        GTEMRelaisController.setObjectName("GTEMRelaisController")
        GTEMRelaisController.resize(721, 476)
        GTEMRelaisController.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QWidget(GTEMRelaisController)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 200, 111, 141))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 91, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sgSwitch_LF = QRadioButton(self.layoutWidget)
        self.sgSwitch_LF.setEnabled(True)
        self.sgSwitch_LF.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.sgSwitch_LF.setChecked(False)
        self.sgSwitch_LF.setObjectName("sgSwitch_LF")
        self.verticalLayout.addWidget(self.sgSwitch_LF)
        self.sgSwitch_HF = QRadioButton(self.layoutWidget)
        self.sgSwitch_HF.setEnabled(True)
        self.sgSwitch_HF.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.sgSwitch_HF.setObjectName("sgSwitch_HF")
        self.verticalLayout.addWidget(self.sgSwitch_HF)
        self.sgSwitch_Direct = QRadioButton(self.layoutWidget)
        self.sgSwitch_Direct.setEnabled(True)
        self.sgSwitch_Direct.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.sgSwitch_Direct.setChecked(True)
        self.sgSwitch_Direct.setObjectName("sgSwitch_Direct")
        self.verticalLayout.addWidget(self.sgSwitch_Direct)
        self.conn_amp_lf = QFrame(self.centralwidget)
        self.conn_amp_lf.setEnabled(False)
        self.conn_amp_lf.setGeometry(QtCore.QRect(170, 230, 231, 16))
        self.conn_amp_lf.setFrameShadow(QFrame.Plain)
        self.conn_amp_lf.setLineWidth(2)
        self.conn_amp_lf.setFrameShape(QFrame.HLine)
#        self.conn_amp_lf.setFrameShadow(QFrame.Sunken)
        self.conn_amp_lf.setObjectName("conn_amp_lf")
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(190, 209, 61, 41))
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_4 = QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 0, 61, 41))
        self.groupBox_4.setAutoFillBackground(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QGroupBox(self.groupBox_4)
        self.groupBox_5.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_5.setAutoFillBackground(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.conn_amp_hf = QFrame(self.centralwidget)
        self.conn_amp_hf.setEnabled(False)
        self.conn_amp_hf.setGeometry(QtCore.QRect(170, 270, 231, 16))
        self.conn_amp_hf.setFrameShadow(QFrame.Plain)
        self.conn_amp_hf.setLineWidth(2)
        self.conn_amp_hf.setFrameShape(QFrame.HLine)
#        self.conn_amp_hf.setFrameShadow(QFrame.Sunken)
        self.conn_amp_hf.setObjectName("conn_amp_hf")
        self.conn_amp_direct = QFrame(self.centralwidget)
        self.conn_amp_direct.setGeometry(QtCore.QRect(170, 300, 231, 16))
        self.conn_amp_direct.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct.setLineWidth(2)
        self.conn_amp_direct.setFrameShape(QFrame.HLine)
#        self.conn_amp_direct.setFrameShadow(QFrame.Sunken)
        self.conn_amp_direct.setObjectName("conn_amp_direct")
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(190, 250, 61, 41))
        self.groupBox_3.setAutoFillBackground(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.frame = QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(400, 220, 31, 101))
        self.frame.setStyleSheet("color: black;")
        self.frame.setFrameShape(QFrame.Box)
        self.frame.setFrameShadow(QFrame.Plain)
        self.frame.setObjectName("frame")
        self.conn_amp_direct_2 = QFrame(self.centralwidget)
        self.conn_amp_direct_2.setGeometry(QtCore.QRect(430, 270, 31, 16))
        self.conn_amp_direct_2.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_2.setLineWidth(2)
        self.conn_amp_direct_2.setFrameShape(QFrame.HLine)
#        self.conn_amp_direct_2.setFrameShadow(QFrame.Sunken)
        self.conn_amp_direct_2.setObjectName("conn_amp_direct_2")
        self.groupBox_6 = QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(270, 210, 41, 41))
        self.groupBox_6.setAutoFillBackground(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox_7 = QGroupBox(self.groupBox_6)
        self.groupBox_7.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_7.setAutoFillBackground(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.groupBox_8 = QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(330, 250, 41, 41))
        self.groupBox_8.setAutoFillBackground(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.groupBox_9 = QGroupBox(self.groupBox_8)
        self.groupBox_9.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_9.setAutoFillBackground(True)
        self.groupBox_9.setObjectName("groupBox_9")
        self.groupBox_10 = QGroupBox(self.centralwidget)
        self.groupBox_10.setGeometry(QtCore.QRect(460, 210, 81, 120))
        self.groupBox_10.setFlat(False)
        self.groupBox_10.setCheckable(False)
        self.groupBox_10.setObjectName("groupBox_10")
        self.layoutWidget_2 = QWidget(self.groupBox_10)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 61, 91))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TxSwitch_Term = QRadioButton(self.layoutWidget_2)
        self.TxSwitch_Term.setEnabled(True)
        self.TxSwitch_Term.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.TxSwitch_Term.setChecked(True)
        self.TxSwitch_Term.setObjectName("TxSwitch_Term")
        self.verticalLayout_2.addWidget(self.TxSwitch_Term)
        self.TxSwitch_GTEM = QRadioButton(self.layoutWidget_2)
        self.TxSwitch_GTEM.setEnabled(True)
        self.TxSwitch_GTEM.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.TxSwitch_GTEM.setChecked(False)
        self.TxSwitch_GTEM.setObjectName("TxSwitch_GTEM")
        self.verticalLayout_2.addWidget(self.TxSwitch_GTEM)
        self.conn_amp_direct_3 = QFrame(self.centralwidget)
        self.conn_amp_direct_3.setEnabled(False)
        self.conn_amp_direct_3.setGeometry(QtCore.QRect(540, 290, 31, 16))
        self.conn_amp_direct_3.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_3.setLineWidth(2)
        self.conn_amp_direct_3.setFrameShape(QFrame.HLine)
#        self.conn_amp_direct_3.setFrameShadow(QFrame.Sunken)
        self.conn_amp_direct_3.setObjectName("conn_amp_direct_3")
        self.groupBox_11 = QGroupBox(self.centralwidget)
        self.groupBox_11.setGeometry(QtCore.QRect(630, 310, 61, 31))
        self.groupBox_11.setAutoFillBackground(True)
        self.groupBox_11.setObjectName("groupBox_11")
        self.groupBox_12 = QGroupBox(self.groupBox_11)
        self.groupBox_12.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_12.setAutoFillBackground(True)
        self.groupBox_12.setObjectName("groupBox_12")
        self.groupBox_25 = QGroupBox(self.groupBox_11)
        self.groupBox_25.setGeometry(QtCore.QRect(0, 40, 61, 31))
        self.groupBox_25.setAutoFillBackground(True)
        self.groupBox_25.setObjectName("groupBox_25")
        self.groupBox_15 = QGroupBox(self.centralwidget)
        self.groupBox_15.setGeometry(QtCore.QRect(640, 230, 41, 31))
        self.groupBox_15.setAutoFillBackground(True)
        self.groupBox_15.setObjectName("groupBox_15")
        self.groupBox_17 = QGroupBox(self.centralwidget)
        self.groupBox_17.setGeometry(QtCore.QRect(10, 247, 31, 31))
        self.groupBox_17.setFlat(False)
        self.groupBox_17.setCheckable(False)
        self.groupBox_17.setObjectName("groupBox_17")
        self.conn_amp_direct_6 = QFrame(self.centralwidget)
        self.conn_amp_direct_6.setGeometry(QtCore.QRect(40, 260, 21, 20))
        self.conn_amp_direct_6.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_6.setLineWidth(2)
        self.conn_amp_direct_6.setFrameShape(QFrame.HLine)
#        self.conn_amp_direct_6.setFrameShadow(QFrame.Sunken)
        self.conn_amp_direct_6.setObjectName("conn_amp_direct_6")
        self.groupBox_18 = QGroupBox(self.centralwidget)
        self.groupBox_18.setGeometry(QtCore.QRect(10, 66, 61, 31))
        self.groupBox_18.setFlat(False)
        self.groupBox_18.setCheckable(False)
        self.groupBox_18.setObjectName("groupBox_18")
        self.groupBox_19 = QGroupBox(self.centralwidget)
        self.groupBox_19.setGeometry(QtCore.QRect(10, 107, 61, 31))
        self.groupBox_19.setFlat(False)
        self.groupBox_19.setCheckable(False)
        self.groupBox_19.setObjectName("groupBox_19")
        self.conn_amp_direct_7 = QFrame(self.centralwidget)
        self.conn_amp_direct_7.setEnabled(False)
        self.conn_amp_direct_7.setGeometry(QtCore.QRect(70, 120, 31, 16))
        self.conn_amp_direct_7.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_7.setLineWidth(2)
        self.conn_amp_direct_7.setFrameShape(QFrame.HLine)
#        self.conn_amp_direct_7.setFrameShadow(QFrame.Sunken)
        self.conn_amp_direct_7.setObjectName("conn_amp_direct_7")
        self.conn_amp_direct_8 = QFrame(self.centralwidget)
        self.conn_amp_direct_8.setEnabled(False)
        self.conn_amp_direct_8.setGeometry(QtCore.QRect(70, 80, 31, 16))
        self.conn_amp_direct_8.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_8.setLineWidth(2)
        self.conn_amp_direct_8.setFrameShape(QFrame.HLine)
#        self.conn_amp_direct_8.setFrameShadow(QFrame.Sunken)
        self.conn_amp_direct_8.setObjectName("conn_amp_direct_8")
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(100, 70, 31, 71))
        self.frame_2.setStyleSheet("color: black;")
        self.frame_2.setFrameShape(QFrame.Box)
        self.frame_2.setFrameShadow(QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.conn_amp_direct_9 = QFrame(self.centralwidget)
        self.conn_amp_direct_9.setEnabled(False)
        self.conn_amp_direct_9.setGeometry(QtCore.QRect(130, 70, 151, 16))
        self.conn_amp_direct_9.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_9.setLineWidth(2)
        self.conn_amp_direct_9.setFrameShape(QFrame.HLine)
#        self.conn_amp_direct_9.setFrameShadow(QFrame.Sunken)
        self.conn_amp_direct_9.setObjectName("conn_amp_direct_9")
        self.conn_amp_direct_10 = QFrame(self.centralwidget)
        self.conn_amp_direct_10.setEnabled(False)
        self.conn_amp_direct_10.setGeometry(QtCore.QRect(130, 80, 211, 16))
        self.conn_amp_direct_10.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_10.setLineWidth(2)
        self.conn_amp_direct_10.setFrameShape(QFrame.HLine)
#        self.conn_amp_direct_10.setFrameShadow(QFrame.Sunken)
        self.conn_amp_direct_10.setObjectName("conn_amp_direct_10")
        self.conn_amp_direct_11 = QFrame(self.centralwidget)
        self.conn_amp_direct_11.setEnabled(False)
        self.conn_amp_direct_11.setGeometry(QtCore.QRect(130, 110, 171, 16))
        self.conn_amp_direct_11.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_11.setLineWidth(2)
        self.conn_amp_direct_11.setFrameShape(QFrame.HLine)
#        self.conn_amp_direct_11.setFrameShadow(QFrame.Sunken)
        self.conn_amp_direct_11.setObjectName("conn_amp_direct_11")
        self.conn_amp_direct_12 = QFrame(self.centralwidget)
        self.conn_amp_direct_12.setEnabled(False)
        self.conn_amp_direct_12.setGeometry(QtCore.QRect(130, 120, 230, 16))
        self.conn_amp_direct_12.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_12.setLineWidth(2)
        self.conn_amp_direct_12.setFrameShape(QFrame.HLine)
#        self.conn_amp_direct_12.setFrameShadow(QFrame.Sunken)
        self.conn_amp_direct_12.setObjectName("conn_amp_direct_12")
        self.conn_amp_direct_13 = QFrame(self.centralwidget)
        self.conn_amp_direct_13.setEnabled(False)
        self.conn_amp_direct_13.setGeometry(QtCore.QRect(270, 77, 20, 150))
        self.conn_amp_direct_13.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_13.setLineWidth(2)
        self.conn_amp_direct_13.setFrameShape(QFrame.VLine)
#        self.conn_amp_direct_13.setFrameShadow(QFrame.Sunken)
        self.conn_amp_direct_13.setObjectName("conn_amp_direct_13")
        self.conn_amp_direct_14 = QFrame(self.centralwidget)
        self.conn_amp_direct_14.setEnabled(False)
        self.conn_amp_direct_14.setGeometry(QtCore.QRect(330, 88, 20, 180))
        self.conn_amp_direct_14.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_14.setLineWidth(2)
        self.conn_amp_direct_14.setFrameShape(QFrame.VLine)
#        self.conn_amp_direct_14.setFrameShadow(QFrame.Sunken)
        self.conn_amp_direct_14.setObjectName("conn_amp_direct_14")
        self.conn_amp_direct_15 = QFrame(self.centralwidget)
        self.conn_amp_direct_15.setEnabled(False)
        self.conn_amp_direct_15.setGeometry(QtCore.QRect(290, 118, 20, 110))
        self.conn_amp_direct_15.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_15.setLineWidth(2)
        self.conn_amp_direct_15.setFrameShape(QFrame.VLine)
#        self.conn_amp_direct_15.setFrameShadow(QFrame.Sunken)
        self.conn_amp_direct_15.setObjectName("conn_amp_direct_15")
        self.conn_amp_direct_16 = QFrame(self.centralwidget)
        self.conn_amp_direct_16.setEnabled(False)
        self.conn_amp_direct_16.setGeometry(QtCore.QRect(350, 128, 20, 140))
        self.conn_amp_direct_16.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_16.setLineWidth(2)
        self.conn_amp_direct_16.setFrameShape(QFrame.VLine)
#        self.conn_amp_direct_16.setFrameShadow(QFrame.Sunken)
        self.conn_amp_direct_16.setObjectName("conn_amp_direct_16")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(440, 70, 161, 71))
        self.pushButton.setObjectName("pushButton")
        self.conn_amp_direct_17 = QFrame(self.centralwidget)
        self.conn_amp_direct_17.setGeometry(QtCore.QRect(600, 320, 31, 16))
        self.conn_amp_direct_17.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_17.setLineWidth(2)
        self.conn_amp_direct_17.setFrameShape(QFrame.HLine)
#        self.conn_amp_direct_17.setFrameShadow(QFrame.Sunken)
        self.conn_amp_direct_17.setObjectName("conn_amp_direct_17")
        self.conn_amp_direct_19 = QFrame(self.centralwidget)
        self.conn_amp_direct_19.setEnabled(False)
        self.conn_amp_direct_19.setGeometry(QtCore.QRect(540, 350, 31, 20))
        self.conn_amp_direct_19.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_19.setLineWidth(2)
        self.conn_amp_direct_19.setFrameShape(QFrame.HLine)
#        self.conn_amp_direct_19.setFrameShadow(QFrame.Sunken)
        self.conn_amp_direct_19.setObjectName("conn_amp_direct_19")
        self.frame_3 = QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(570, 280, 31, 101))
        self.frame_3.setStyleSheet("color: black;")
        self.frame_3.setFrameShape(QFrame.Box)
        self.frame_3.setFrameShadow(QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.conn_amp_direct_5 = QFrame(self.centralwidget)
        self.conn_amp_direct_5.setGeometry(QtCore.QRect(540, 240, 101, 16))
        self.conn_amp_direct_5.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_5.setLineWidth(2)
        self.conn_amp_direct_5.setFrameShape(QFrame.HLine)
#        self.conn_amp_direct_5.setFrameShadow(QFrame.Sunken)
        self.conn_amp_direct_5.setObjectName("conn_amp_direct_5")
        self.groupBox_13 = QGroupBox(self.centralwidget)
        self.groupBox_13.setGeometry(QtCore.QRect(460, 330, 81, 120))
        self.groupBox_13.setFlat(False)
        self.groupBox_13.setCheckable(False)
        self.groupBox_13.setObjectName("groupBox_13")
        self.layoutWidget_3 = QWidget(self.groupBox_13)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 20, 61, 91))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_3 = QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.RxSwitch_GTEM = QRadioButton(self.layoutWidget_3)
        self.RxSwitch_GTEM.setEnabled(True)
        self.RxSwitch_GTEM.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.RxSwitch_GTEM.setChecked(False)
        self.RxSwitch_GTEM.setObjectName("RxSwitch_GTEM")
        self.verticalLayout_3.addWidget(self.RxSwitch_GTEM)
        self.RxSwitch_Term = QRadioButton(self.layoutWidget_3)
        self.RxSwitch_Term.setEnabled(True)
        self.RxSwitch_Term.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.RxSwitch_Term.setChecked(True)
        self.RxSwitch_Term.setObjectName("RxSwitch_Term")
        self.verticalLayout_3.addWidget(self.RxSwitch_Term)
        self.groupBox_16 = QGroupBox(self.centralwidget)
        self.groupBox_16.setGeometry(QtCore.QRect(640, 400, 41, 31))
        self.groupBox_16.setAutoFillBackground(True)
        self.groupBox_16.setObjectName("groupBox_16")
        self.conn_amp_direct_18 = QFrame(self.centralwidget)
        self.conn_amp_direct_18.setGeometry(QtCore.QRect(540, 410, 101, 16))
        self.conn_amp_direct_18.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_18.setLineWidth(2)
        self.conn_amp_direct_18.setFrameShape(QFrame.HLine)
#        self.conn_amp_direct_18.setFrameShadow(QFrame.Sunken)
        self.conn_amp_direct_18.setObjectName("conn_amp_direct_18")
        self.groupBox_14 = QGroupBox(self.centralwidget)
        self.groupBox_14.setGeometry(QtCore.QRect(10, 340, 81, 91))
        self.groupBox_14.setFlat(False)
        self.groupBox_14.setCheckable(False)
        self.groupBox_14.setObjectName("groupBox_14")
        self.layoutWidget_4 = QWidget(self.groupBox_14)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 20, 62, 61))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_4 = QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.RxSwitch_30M = QRadioButton(self.layoutWidget_4)
        self.RxSwitch_30M.setEnabled(True)
        self.RxSwitch_30M.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.RxSwitch_30M.setChecked(True)
        self.RxSwitch_30M.setObjectName("RxSwitch_30M")
        self.verticalLayout_4.addWidget(self.RxSwitch_30M)
        self.RxSwitch_3G = QRadioButton(self.layoutWidget_4)
        self.RxSwitch_3G.setEnabled(True)
        self.RxSwitch_3G.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.RxSwitch_3G.setChecked(False)
        self.RxSwitch_3G.setObjectName("RxSwitch_3G")
        self.verticalLayout_4.addWidget(self.RxSwitch_3G)
        self.conn_amp_direct_20 = QFrame(self.centralwidget)
        self.conn_amp_direct_20.setEnabled(True)
        self.conn_amp_direct_20.setGeometry(QtCore.QRect(90, 380, 371, 20))
        self.conn_amp_direct_20.setFrameShadow(QFrame.Plain)
        self.conn_amp_direct_20.setLineWidth(2)
        self.conn_amp_direct_20.setFrameShape(QFrame.HLine)
#        self.conn_amp_direct_20.setFrameShadow(QFrame.Sunken)
        self.conn_amp_direct_20.setObjectName("conn_amp_direct_20")
        GTEMRelaisController.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(GTEMRelaisController)
        self.statusbar.setObjectName("statusbar")
        GTEMRelaisController.setStatusBar(self.statusbar)

        self.retranslateUi(GTEMRelaisController)
        self.sgSwitch_Direct.toggled['bool'].connect(self.conn_amp_direct.setEnabled)
        self.sgSwitch_HF.toggled['bool'].connect(self.conn_amp_hf.setEnabled)
        self.sgSwitch_LF.toggled['bool'].connect(self.conn_amp_lf.setEnabled)
        self.sgSwitch_HF.toggled['bool'].connect(self.conn_amp_direct_14.setEnabled)
        self.sgSwitch_HF.toggled['bool'].connect(self.conn_amp_direct_16.setEnabled)
        self.sgSwitch_LF.toggled['bool'].connect(self.conn_amp_direct_13.setEnabled)
        self.sgSwitch_LF.toggled['bool'].connect(self.conn_amp_direct_15.setEnabled)
        self.sgSwitch_LF.toggled['bool'].connect(self.conn_amp_direct_11.setEnabled)
        self.sgSwitch_LF.toggled['bool'].connect(self.conn_amp_direct_9.setEnabled)
        self.sgSwitch_HF.toggled['bool'].connect(self.conn_amp_direct_10.setEnabled)
        self.sgSwitch_HF.toggled['bool'].connect(self.conn_amp_direct_12.setEnabled)
        self.pushButton.clicked.connect(self.sgSwitch_Direct.click)
        self.sgSwitch_Direct.toggled['bool'].connect(self.conn_amp_direct_7.setDisabled)
        self.sgSwitch_Direct.toggled['bool'].connect(self.conn_amp_direct_8.setDisabled)
        self.sgSwitch_HF.toggled['bool'].connect(self.conn_amp_direct_7.setEnabled)
        self.sgSwitch_HF.toggled['bool'].connect(self.conn_amp_direct_8.setEnabled)
        self.sgSwitch_LF.toggled['bool'].connect(self.conn_amp_direct_7.setEnabled)
        self.sgSwitch_LF.toggled['bool'].connect(self.conn_amp_direct_8.setEnabled)
        self.TxSwitch_Term.toggled['bool'].connect(self.conn_amp_direct_5.setEnabled)
        self.TxSwitch_GTEM.toggled['bool'].connect(self.conn_amp_direct_3.setEnabled)
        self.pushButton.clicked.connect(self.TxSwitch_Term.click)
        self.pushButton.clicked.connect(self.RxSwitch_Term.click)
        self.pushButton.clicked.connect(self.RxSwitch_30M.click)
        self.RxSwitch_GTEM.toggled['bool'].connect(self.conn_amp_direct_19.setEnabled)
        self.RxSwitch_Term.toggled['bool'].connect(self.conn_amp_direct_18.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(GTEMRelaisController)

    def retranslateUi(self, GTEMRelaisController):
        _translate = QtCore.QCoreApplication.translate
        GTEMRelaisController.setWindowTitle(_translate("GTEMRelaisController", "GTEM Matrix Switch Controller "))
        self.groupBox.setTitle(_translate("GTEMRelaisController", "Switch 1"))
        self.sgSwitch_LF.setText(_translate("GTEMRelaisController", "LF"))
        self.sgSwitch_HF.setText(_translate("GTEMRelaisController", "HF"))
        self.sgSwitch_Direct.setText(_translate("GTEMRelaisController", "Direct"))
        self.groupBox_2.setTitle(_translate("GTEMRelaisController", "Amp LF"))
        self.groupBox_4.setTitle(_translate("GTEMRelaisController", "Amp LF"))
        self.groupBox_5.setTitle(_translate("GTEMRelaisController", "Amp LF"))
        self.groupBox_3.setTitle(_translate("GTEMRelaisController", "Amp HF"))
        self.groupBox_6.setTitle(_translate("GTEMRelaisController", "DC LF"))
        self.groupBox_7.setTitle(_translate("GTEMRelaisController", "Amp LF"))
        self.groupBox_8.setTitle(_translate("GTEMRelaisController", "DC HF"))
        self.groupBox_9.setTitle(_translate("GTEMRelaisController", "Amp LF"))
        self.groupBox_10.setTitle(_translate("GTEMRelaisController", "Switch 2"))
        self.TxSwitch_Term.setText(_translate("GTEMRelaisController", "Term"))
        self.TxSwitch_GTEM.setText(_translate("GTEMRelaisController", "GTEM"))
        self.groupBox_11.setTitle(_translate("GTEMRelaisController", "GTEM"))
        self.groupBox_12.setTitle(_translate("GTEMRelaisController", "Amp LF"))
        self.groupBox_25.setTitle(_translate("GTEMRelaisController", "Horn"))
        self.groupBox_15.setTitle(_translate("GTEMRelaisController", "Term"))
        self.groupBox_17.setTitle(_translate("GTEMRelaisController", "SG"))
        self.groupBox_18.setTitle(_translate("GTEMRelaisController", "PM FWD"))
        self.groupBox_19.setTitle(_translate("GTEMRelaisController", "PM REV"))
        self.pushButton.setText(_translate("GTEMRelaisController", "Safe Setting"))
        self.groupBox_13.setTitle(_translate("GTEMRelaisController", "Switch 3"))
        self.RxSwitch_GTEM.setText(_translate("GTEMRelaisController", "GTEM"))
        self.RxSwitch_Term.setText(_translate("GTEMRelaisController", "Term"))
        self.groupBox_16.setTitle(_translate("GTEMRelaisController", "Term"))
        self.groupBox_14.setTitle(_translate("GTEMRelaisController", "Rec"))
        self.RxSwitch_30M.setText(_translate("GTEMRelaisController", "30M"))
        self.RxSwitch_3G.setText(_translate("GTEMRelaisController", "3G"))
