# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RCSwitch.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtWidgets


class Ui_ReverbChamberRelaisController(object):
    def setupUi(self, ReverbChamberRelaisController):
        ReverbChamberRelaisController.setObjectName("ReverbChamberRelaisController")
        ReverbChamberRelaisController.resize(692, 494)
        ReverbChamberRelaisController.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(ReverbChamberRelaisController)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 200, 111, 141))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 91, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sgSwitch_LF = QtWidgets.QRadioButton(self.layoutWidget)
        self.sgSwitch_LF.setEnabled(True)
        self.sgSwitch_LF.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.sgSwitch_LF.setChecked(False)
        self.sgSwitch_LF.setObjectName("sgSwitch_LF")
        self.verticalLayout.addWidget(self.sgSwitch_LF)
        self.sgSwitch_HF = QtWidgets.QRadioButton(self.layoutWidget)
        self.sgSwitch_HF.setEnabled(True)
        self.sgSwitch_HF.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.sgSwitch_HF.setObjectName("sgSwitch_HF")
        self.verticalLayout.addWidget(self.sgSwitch_HF)
        self.sgSwitch_Direct = QtWidgets.QRadioButton(self.layoutWidget)
        self.sgSwitch_Direct.setEnabled(True)
        self.sgSwitch_Direct.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.sgSwitch_Direct.setChecked(True)
        self.sgSwitch_Direct.setObjectName("sgSwitch_Direct")
        self.verticalLayout.addWidget(self.sgSwitch_Direct)
        self.conn_amp_lf = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_lf.setEnabled(False)
        self.conn_amp_lf.setGeometry(QtCore.QRect(170, 230, 231, 16))
        self.conn_amp_lf.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_lf.setLineWidth(2)
        self.conn_amp_lf.setFrameShape(QtWidgets.QFrame.HLine)
        self.conn_amp_lf.setObjectName("conn_amp_lf")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(190, 209, 61, 41))
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 0, 61, 41))
        self.groupBox_4.setAutoFillBackground(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_5.setAutoFillBackground(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.conn_amp_hf = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_hf.setEnabled(False)
        self.conn_amp_hf.setGeometry(QtCore.QRect(170, 270, 231, 16))
        self.conn_amp_hf.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_hf.setLineWidth(2)
        self.conn_amp_hf.setFrameShape(QtWidgets.QFrame.HLine)
        self.conn_amp_hf.setObjectName("conn_amp_hf")
        self.conn_amp_direct = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_direct.setGeometry(QtCore.QRect(170, 300, 231, 16))
        self.conn_amp_direct.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_direct.setLineWidth(2)
        self.conn_amp_direct.setFrameShape(QtWidgets.QFrame.HLine)
        self.conn_amp_direct.setObjectName("conn_amp_direct")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(190, 250, 61, 41))
        self.groupBox_3.setAutoFillBackground(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(400, 220, 31, 101))
        self.frame.setStyleSheet("color: black;")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.conn_amp_direct_2 = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_direct_2.setGeometry(QtCore.QRect(430, 270, 31, 16))
        self.conn_amp_direct_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_direct_2.setLineWidth(2)
        self.conn_amp_direct_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.conn_amp_direct_2.setObjectName("conn_amp_direct_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(270, 210, 41, 41))
        self.groupBox_6.setAutoFillBackground(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_7.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_7.setAutoFillBackground(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(330, 250, 41, 41))
        self.groupBox_8.setAutoFillBackground(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_9.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_9.setAutoFillBackground(True)
        self.groupBox_9.setObjectName("groupBox_9")
        self.groupBox_10 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_10.setGeometry(QtCore.QRect(460, 200, 111, 141))
        self.groupBox_10.setFlat(False)
        self.groupBox_10.setCheckable(False)
        self.groupBox_10.setObjectName("groupBox_10")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_10)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 91, 111))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TxSwitch_LF = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.TxSwitch_LF.setEnabled(True)
        self.TxSwitch_LF.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.TxSwitch_LF.setChecked(False)
        self.TxSwitch_LF.setObjectName("TxSwitch_LF")
        self.verticalLayout_2.addWidget(self.TxSwitch_LF)
        self.TxSwitch_HF = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.TxSwitch_HF.setEnabled(True)
        self.TxSwitch_HF.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.TxSwitch_HF.setObjectName("TxSwitch_HF")
        self.verticalLayout_2.addWidget(self.TxSwitch_HF)
        self.TxSwitch_Term = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.TxSwitch_Term.setEnabled(True)
        self.TxSwitch_Term.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.TxSwitch_Term.setChecked(True)
        self.TxSwitch_Term.setObjectName("TxSwitch_Term")
        self.verticalLayout_2.addWidget(self.TxSwitch_Term)
        self.conn_amp_direct_3 = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_direct_3.setEnabled(False)
        self.conn_amp_direct_3.setGeometry(QtCore.QRect(570, 230, 31, 16))
        self.conn_amp_direct_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_direct_3.setLineWidth(2)
        self.conn_amp_direct_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.conn_amp_direct_3.setObjectName("conn_amp_direct_3")
        self.conn_amp_direct_4 = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_direct_4.setEnabled(False)
        self.conn_amp_direct_4.setGeometry(QtCore.QRect(570, 264, 31, 16))
        self.conn_amp_direct_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_direct_4.setLineWidth(2)
        self.conn_amp_direct_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.conn_amp_direct_4.setObjectName("conn_amp_direct_4")
        self.conn_amp_direct_5 = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_direct_5.setGeometry(QtCore.QRect(570, 300, 31, 16))
        self.conn_amp_direct_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_direct_5.setLineWidth(2)
        self.conn_amp_direct_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.conn_amp_direct_5.setObjectName("conn_amp_direct_5")
        self.groupBox_11 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_11.setGeometry(QtCore.QRect(600, 215, 61, 31))
        self.groupBox_11.setAutoFillBackground(True)
        self.groupBox_11.setObjectName("groupBox_11")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_11)
        self.groupBox_12.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_12.setAutoFillBackground(True)
        self.groupBox_12.setObjectName("groupBox_12")
        self.groupBox_23 = QtWidgets.QGroupBox(self.groupBox_11)
        self.groupBox_23.setGeometry(QtCore.QRect(0, 70, 61, 31))
        self.groupBox_23.setAutoFillBackground(True)
        self.groupBox_23.setObjectName("groupBox_23")
        self.groupBox_24 = QtWidgets.QGroupBox(self.groupBox_23)
        self.groupBox_24.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_24.setAutoFillBackground(True)
        self.groupBox_24.setObjectName("groupBox_24")
        self.groupBox_25 = QtWidgets.QGroupBox(self.groupBox_11)
        self.groupBox_25.setGeometry(QtCore.QRect(0, 40, 61, 31))
        self.groupBox_25.setAutoFillBackground(True)
        self.groupBox_25.setObjectName("groupBox_25")
        self.groupBox_26 = QtWidgets.QGroupBox(self.groupBox_25)
        self.groupBox_26.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_26.setAutoFillBackground(True)
        self.groupBox_26.setObjectName("groupBox_26")
        self.groupBox_13 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_13.setGeometry(QtCore.QRect(600, 250, 61, 31))
        self.groupBox_13.setAutoFillBackground(True)
        self.groupBox_13.setObjectName("groupBox_13")
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_14.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_14.setAutoFillBackground(True)
        self.groupBox_14.setObjectName("groupBox_14")
        self.groupBox_15 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_15.setGeometry(QtCore.QRect(600, 285, 61, 31))
        self.groupBox_15.setAutoFillBackground(True)
        self.groupBox_15.setObjectName("groupBox_15")
        self.groupBox_16 = QtWidgets.QGroupBox(self.groupBox_15)
        self.groupBox_16.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_16.setAutoFillBackground(True)
        self.groupBox_16.setObjectName("groupBox_16")
        self.groupBox_17 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_17.setGeometry(QtCore.QRect(10, 247, 31, 31))
        self.groupBox_17.setFlat(False)
        self.groupBox_17.setCheckable(False)
        self.groupBox_17.setObjectName("groupBox_17")
        self.conn_amp_direct_6 = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_direct_6.setGeometry(QtCore.QRect(40, 260, 21, 20))
        self.conn_amp_direct_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_direct_6.setLineWidth(2)
        self.conn_amp_direct_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.conn_amp_direct_6.setObjectName("conn_amp_direct_6")
        self.groupBox_18 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_18.setGeometry(QtCore.QRect(10, 66, 61, 31))
        self.groupBox_18.setFlat(False)
        self.groupBox_18.setCheckable(False)
        self.groupBox_18.setObjectName("groupBox_18")
        self.groupBox_19 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_19.setGeometry(QtCore.QRect(10, 107, 61, 31))
        self.groupBox_19.setFlat(False)
        self.groupBox_19.setCheckable(False)
        self.groupBox_19.setObjectName("groupBox_19")
        self.conn_amp_direct_7 = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_direct_7.setEnabled(False)
        self.conn_amp_direct_7.setGeometry(QtCore.QRect(70, 120, 31, 16))
        self.conn_amp_direct_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_direct_7.setLineWidth(2)
        self.conn_amp_direct_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.conn_amp_direct_7.setObjectName("conn_amp_direct_7")
        self.conn_amp_direct_8 = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_direct_8.setEnabled(False)
        self.conn_amp_direct_8.setGeometry(QtCore.QRect(70, 80, 31, 16))
        self.conn_amp_direct_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_direct_8.setLineWidth(2)
        self.conn_amp_direct_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.conn_amp_direct_8.setObjectName("conn_amp_direct_8")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(100, 70, 31, 71))
        self.frame_2.setStyleSheet("color: black;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.conn_amp_direct_9 = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_direct_9.setEnabled(False)
        self.conn_amp_direct_9.setGeometry(QtCore.QRect(130, 70, 151, 16))
        self.conn_amp_direct_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_direct_9.setLineWidth(2)
        self.conn_amp_direct_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.conn_amp_direct_9.setObjectName("conn_amp_direct_9")
        self.conn_amp_direct_10 = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_direct_10.setEnabled(False)
        self.conn_amp_direct_10.setGeometry(QtCore.QRect(130, 80, 211, 16))
        self.conn_amp_direct_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_direct_10.setLineWidth(2)
        self.conn_amp_direct_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.conn_amp_direct_10.setObjectName("conn_amp_direct_10")
        self.conn_amp_direct_11 = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_direct_11.setEnabled(False)
        self.conn_amp_direct_11.setGeometry(QtCore.QRect(130, 110, 171, 16))
        self.conn_amp_direct_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_direct_11.setLineWidth(2)
        self.conn_amp_direct_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.conn_amp_direct_11.setObjectName("conn_amp_direct_11")
        self.conn_amp_direct_12 = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_direct_12.setEnabled(False)
        self.conn_amp_direct_12.setGeometry(QtCore.QRect(130, 120, 230, 16))
        self.conn_amp_direct_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_direct_12.setLineWidth(2)
        self.conn_amp_direct_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.conn_amp_direct_12.setObjectName("conn_amp_direct_12")
        self.conn_amp_direct_13 = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_direct_13.setEnabled(False)
        self.conn_amp_direct_13.setGeometry(QtCore.QRect(270, 77, 20, 150))
        self.conn_amp_direct_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_direct_13.setLineWidth(2)
        self.conn_amp_direct_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.conn_amp_direct_13.setObjectName("conn_amp_direct_13")
        self.conn_amp_direct_14 = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_direct_14.setEnabled(False)
        self.conn_amp_direct_14.setGeometry(QtCore.QRect(330, 88, 20, 180))
        self.conn_amp_direct_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_direct_14.setLineWidth(2)
        self.conn_amp_direct_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.conn_amp_direct_14.setObjectName("conn_amp_direct_14")
        self.conn_amp_direct_15 = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_direct_15.setEnabled(False)
        self.conn_amp_direct_15.setGeometry(QtCore.QRect(290, 118, 20, 110))
        self.conn_amp_direct_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_direct_15.setLineWidth(2)
        self.conn_amp_direct_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.conn_amp_direct_15.setObjectName("conn_amp_direct_15")
        self.conn_amp_direct_16 = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_direct_16.setEnabled(False)
        self.conn_amp_direct_16.setGeometry(QtCore.QRect(350, 128, 20, 140))
        self.conn_amp_direct_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_direct_16.setLineWidth(2)
        self.conn_amp_direct_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.conn_amp_direct_16.setObjectName("conn_amp_direct_16")
        self.conn_amp_direct_17 = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_direct_17.setGeometry(QtCore.QRect(430, 410, 31, 16))
        self.conn_amp_direct_17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_direct_17.setLineWidth(2)
        self.conn_amp_direct_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.conn_amp_direct_17.setObjectName("conn_amp_direct_17")
        self.conn_amp_direct_18 = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_direct_18.setEnabled(True)
        self.conn_amp_direct_18.setGeometry(QtCore.QRect(570, 390, 31, 16))
        self.conn_amp_direct_18.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_direct_18.setLineWidth(2)
        self.conn_amp_direct_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.conn_amp_direct_18.setObjectName("conn_amp_direct_18")
        self.groupBox_20 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_20.setGeometry(QtCore.QRect(460, 360, 111, 101))
        self.groupBox_20.setFlat(False)
        self.groupBox_20.setCheckable(False)
        self.groupBox_20.setObjectName("groupBox_20")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_20)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 20, 91, 71))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.RxSwitch_LF = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.RxSwitch_LF.setEnabled(True)
        self.RxSwitch_LF.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.RxSwitch_LF.setChecked(True)
        self.RxSwitch_LF.setObjectName("RxSwitch_LF")
        self.verticalLayout_3.addWidget(self.RxSwitch_LF)
        self.RxSwitch_HF = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.RxSwitch_HF.setEnabled(True)
        self.RxSwitch_HF.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.RxSwitch_HF.setObjectName("RxSwitch_HF")
        self.verticalLayout_3.addWidget(self.RxSwitch_HF)
        self.conn_amp_direct_19 = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_direct_19.setEnabled(False)
        self.conn_amp_direct_19.setGeometry(QtCore.QRect(570, 430, 31, 16))
        self.conn_amp_direct_19.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_direct_19.setLineWidth(2)
        self.conn_amp_direct_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.conn_amp_direct_19.setObjectName("conn_amp_direct_19")
        self.groupBox_27 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_27.setGeometry(QtCore.QRect(600, 374, 61, 31))
        self.groupBox_27.setAutoFillBackground(True)
        self.groupBox_27.setObjectName("groupBox_27")
        self.groupBox_28 = QtWidgets.QGroupBox(self.groupBox_27)
        self.groupBox_28.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_28.setAutoFillBackground(True)
        self.groupBox_28.setObjectName("groupBox_28")
        self.groupBox_31 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_31.setGeometry(QtCore.QRect(600, 413, 61, 31))
        self.groupBox_31.setAutoFillBackground(True)
        self.groupBox_31.setObjectName("groupBox_31")
        self.groupBox_32 = QtWidgets.QGroupBox(self.groupBox_31)
        self.groupBox_32.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_32.setAutoFillBackground(True)
        self.groupBox_32.setObjectName("groupBox_32")
        self.conn_amp_direct_20 = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_direct_20.setEnabled(True)
        self.conn_amp_direct_20.setGeometry(QtCore.QRect(240, 390, 81, 20))
        self.conn_amp_direct_20.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_direct_20.setLineWidth(2)
        self.conn_amp_direct_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.conn_amp_direct_20.setObjectName("conn_amp_direct_20")
        self.conn_amp_direct_21 = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_direct_21.setEnabled(False)
        self.conn_amp_direct_21.setGeometry(QtCore.QRect(240, 420, 81, 20))
        self.conn_amp_direct_21.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_direct_21.setLineWidth(2)
        self.conn_amp_direct_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.conn_amp_direct_21.setObjectName("conn_amp_direct_21")
        self.groupBox_29 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_29.setGeometry(QtCore.QRect(320, 360, 111, 101))
        self.groupBox_29.setFlat(False)
        self.groupBox_29.setCheckable(False)
        self.groupBox_29.setObjectName("groupBox_29")
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_29)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 20, 91, 71))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.AttSwitch_On = QtWidgets.QRadioButton(self.layoutWidget_4)
        self.AttSwitch_On.setEnabled(True)
        self.AttSwitch_On.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AttSwitch_On.setChecked(True)
        self.AttSwitch_On.setObjectName("AttSwitch_On")
        self.verticalLayout_4.addWidget(self.AttSwitch_On)
        self.AttSwitch_Off = QtWidgets.QRadioButton(self.layoutWidget_4)
        self.AttSwitch_Off.setEnabled(True)
        self.AttSwitch_Off.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AttSwitch_Off.setObjectName("AttSwitch_Off")
        self.verticalLayout_4.addWidget(self.AttSwitch_Off)
        self.conn_amp_direct_22 = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_direct_22.setGeometry(QtCore.QRect(180, 410, 31, 16))
        self.conn_amp_direct_22.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_direct_22.setLineWidth(2)
        self.conn_amp_direct_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.conn_amp_direct_22.setObjectName("conn_amp_direct_22")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(210, 390, 31, 51))
        self.frame_3.setStyleSheet("color: black;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.groupBox_30 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_30.setGeometry(QtCore.QRect(260, 370, 41, 41))
        self.groupBox_30.setAutoFillBackground(True)
        self.groupBox_30.setObjectName("groupBox_30")
        self.conn_amp_direct_23 = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_direct_23.setEnabled(False)
        self.conn_amp_direct_23.setGeometry(QtCore.QRect(81, 420, 20, 20))
        self.conn_amp_direct_23.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_direct_23.setLineWidth(2)
        self.conn_amp_direct_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.conn_amp_direct_23.setObjectName("conn_amp_direct_23")
        self.groupBox_33 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_33.setGeometry(QtCore.QRect(100, 360, 81, 101))
        self.groupBox_33.setFlat(False)
        self.groupBox_33.setCheckable(False)
        self.groupBox_33.setObjectName("groupBox_33")
        self.layoutWidget_5 = QtWidgets.QWidget(self.groupBox_33)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 20, 61, 71))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.RxSwitch_PM = QtWidgets.QRadioButton(self.layoutWidget_5)
        self.RxSwitch_PM.setEnabled(True)
        self.RxSwitch_PM.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.RxSwitch_PM.setChecked(True)
        self.RxSwitch_PM.setObjectName("RxSwitch_PM")
        self.verticalLayout_5.addWidget(self.RxSwitch_PM)
        self.RxSwitch_Rec = QtWidgets.QRadioButton(self.layoutWidget_5)
        self.RxSwitch_Rec.setEnabled(True)
        self.RxSwitch_Rec.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.RxSwitch_Rec.setObjectName("RxSwitch_Rec")
        self.verticalLayout_5.addWidget(self.RxSwitch_Rec)
        self.conn_amp_direct_25 = QtWidgets.QFrame(self.centralwidget)
        self.conn_amp_direct_25.setEnabled(True)
        self.conn_amp_direct_25.setGeometry(QtCore.QRect(80, 390, 21, 20))
        self.conn_amp_direct_25.setFrameShadow(QtWidgets.QFrame.Plain)
        self.conn_amp_direct_25.setLineWidth(2)
        self.conn_amp_direct_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.conn_amp_direct_25.setObjectName("conn_amp_direct_25")
        self.groupBox_34 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_34.setGeometry(QtCore.QRect(30, 377, 51, 31))
        self.groupBox_34.setFlat(False)
        self.groupBox_34.setCheckable(False)
        self.groupBox_34.setObjectName("groupBox_34")
        self.groupBox_35 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_35.setGeometry(QtCore.QRect(30, 407, 51, 31))
        self.groupBox_35.setFlat(False)
        self.groupBox_35.setCheckable(False)
        self.groupBox_35.setObjectName("groupBox_35")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(440, 70, 161, 71))
        self.pushButton.setObjectName("pushButton")
        self.conn_amp_direct_14.raise_()
        self.conn_amp_direct_15.raise_()
        self.conn_amp_direct_16.raise_()
        self.conn_amp_direct_13.raise_()
        self.conn_amp_lf.raise_()
        self.conn_amp_hf.raise_()
        self.conn_amp_direct.raise_()
        self.conn_amp_direct_2.raise_()
        self.conn_amp_direct_3.raise_()
        self.conn_amp_direct_4.raise_()
        self.conn_amp_direct_5.raise_()
        self.conn_amp_direct_6.raise_()
        self.conn_amp_direct_9.raise_()
        self.conn_amp_direct_10.raise_()
        self.conn_amp_direct_11.raise_()
        self.conn_amp_direct_12.raise_()
        self.conn_amp_direct_17.raise_()
        self.conn_amp_direct_18.raise_()
        self.conn_amp_direct_7.raise_()
        self.conn_amp_direct_8.raise_()
        self.conn_amp_direct_19.raise_()
        self.conn_amp_direct_20.raise_()
        self.conn_amp_direct_21.raise_()
        self.conn_amp_direct_22.raise_()
        self.conn_amp_direct_23.raise_()
        self.conn_amp_direct_25.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.groupBox_6.raise_()
        self.groupBox_8.raise_()
        self.groupBox_10.raise_()
        self.groupBox_11.raise_()
        self.groupBox_13.raise_()
        self.groupBox_15.raise_()
        self.groupBox_17.raise_()
        self.groupBox_18.raise_()
        self.groupBox_19.raise_()
        self.groupBox_20.raise_()
        self.groupBox_27.raise_()
        self.groupBox_31.raise_()
        self.groupBox_29.raise_()
        self.groupBox_30.raise_()
        self.groupBox_33.raise_()
        self.groupBox_34.raise_()
        self.groupBox_35.raise_()
        self.pushButton.raise_()
        ReverbChamberRelaisController.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ReverbChamberRelaisController)
        self.statusbar.setObjectName("statusbar")
        ReverbChamberRelaisController.setStatusBar(self.statusbar)

        self.retranslateUi(ReverbChamberRelaisController)
        self.sgSwitch_Direct.toggled['bool'].connect(self.conn_amp_direct.setEnabled)
        self.sgSwitch_HF.toggled['bool'].connect(self.conn_amp_hf.setEnabled)
        self.sgSwitch_LF.toggled['bool'].connect(self.conn_amp_lf.setEnabled)
        self.sgSwitch_HF.toggled['bool'].connect(self.conn_amp_direct_14.setEnabled)
        self.sgSwitch_HF.toggled['bool'].connect(self.conn_amp_direct_16.setEnabled)
        self.sgSwitch_LF.toggled['bool'].connect(self.conn_amp_direct_13.setEnabled)
        self.sgSwitch_LF.toggled['bool'].connect(self.conn_amp_direct_15.setEnabled)
        self.sgSwitch_LF.toggled['bool'].connect(self.conn_amp_direct_11.setEnabled)
        self.sgSwitch_LF.toggled['bool'].connect(self.conn_amp_direct_9.setEnabled)
        self.sgSwitch_HF.toggled['bool'].connect(self.conn_amp_direct_10.setEnabled)
        self.sgSwitch_HF.toggled['bool'].connect(self.conn_amp_direct_12.setEnabled)
        self.TxSwitch_Term.toggled['bool'].connect(self.conn_amp_direct_5.setEnabled)
        self.TxSwitch_HF.toggled['bool'].connect(self.conn_amp_direct_4.setEnabled)
        self.TxSwitch_LF.toggled['bool'].connect(self.conn_amp_direct_3.setEnabled)
        self.RxSwitch_LF.toggled['bool'].connect(self.conn_amp_direct_18.setEnabled)
        self.RxSwitch_HF.toggled['bool'].connect(self.conn_amp_direct_19.setEnabled)
        self.RxSwitch_PM.toggled['bool'].connect(self.conn_amp_direct_25.setEnabled)
        self.RxSwitch_Rec.toggled['bool'].connect(self.conn_amp_direct_23.setEnabled)
        self.pushButton.clicked.connect(self.TxSwitch_Term.click)
        self.pushButton.clicked.connect(self.sgSwitch_Direct.click)
        self.pushButton.clicked.connect(self.AttSwitch_On.click)
        self.sgSwitch_Direct.toggled['bool'].connect(self.conn_amp_direct_7.setDisabled)
        self.sgSwitch_Direct.toggled['bool'].connect(self.conn_amp_direct_8.setDisabled)
        self.sgSwitch_HF.toggled['bool'].connect(self.conn_amp_direct_7.setEnabled)
        self.sgSwitch_HF.toggled['bool'].connect(self.conn_amp_direct_8.setEnabled)
        self.sgSwitch_LF.toggled['bool'].connect(self.conn_amp_direct_7.setEnabled)
        self.sgSwitch_LF.toggled['bool'].connect(self.conn_amp_direct_8.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ReverbChamberRelaisController)

    def retranslateUi(self, ReverbChamberRelaisController):
        _translate = QtCore.QCoreApplication.translate
        ReverbChamberRelaisController.setWindowTitle(_translate("ReverbChamberRelaisController", "Reverb Chamber Matrix Switch Controller "))
        self.groupBox.setTitle(_translate("ReverbChamberRelaisController", "Switch 1"))
        self.sgSwitch_LF.setText(_translate("ReverbChamberRelaisController", "LF"))
        self.sgSwitch_HF.setText(_translate("ReverbChamberRelaisController", "HF"))
        self.sgSwitch_Direct.setText(_translate("ReverbChamberRelaisController", "Direct"))
        self.groupBox_2.setTitle(_translate("ReverbChamberRelaisController", "Amp LF"))
        self.groupBox_4.setTitle(_translate("ReverbChamberRelaisController", "Amp LF"))
        self.groupBox_5.setTitle(_translate("ReverbChamberRelaisController", "Amp LF"))
        self.groupBox_3.setTitle(_translate("ReverbChamberRelaisController", "Amp HF"))
        self.groupBox_6.setTitle(_translate("ReverbChamberRelaisController", "DC LF"))
        self.groupBox_7.setTitle(_translate("ReverbChamberRelaisController", "Amp LF"))
        self.groupBox_8.setTitle(_translate("ReverbChamberRelaisController", "DC HF"))
        self.groupBox_9.setTitle(_translate("ReverbChamberRelaisController", "Amp LF"))
        self.groupBox_10.setTitle(_translate("ReverbChamberRelaisController", "Switch 2"))
        self.TxSwitch_LF.setText(_translate("ReverbChamberRelaisController", "LogPer"))
        self.TxSwitch_HF.setText(_translate("ReverbChamberRelaisController", "Horn"))
        self.TxSwitch_Term.setText(_translate("ReverbChamberRelaisController", "Term"))
        self.groupBox_11.setTitle(_translate("ReverbChamberRelaisController", "LogPer"))
        self.groupBox_12.setTitle(_translate("ReverbChamberRelaisController", "Amp LF"))
        self.groupBox_23.setTitle(_translate("ReverbChamberRelaisController", "Term"))
        self.groupBox_24.setTitle(_translate("ReverbChamberRelaisController", "Amp LF"))
        self.groupBox_25.setTitle(_translate("ReverbChamberRelaisController", "Horn"))
        self.groupBox_26.setTitle(_translate("ReverbChamberRelaisController", "Amp LF"))
        self.groupBox_13.setTitle(_translate("ReverbChamberRelaisController", "Horn"))
        self.groupBox_14.setTitle(_translate("ReverbChamberRelaisController", "Amp LF"))
        self.groupBox_15.setTitle(_translate("ReverbChamberRelaisController", "Term"))
        self.groupBox_16.setTitle(_translate("ReverbChamberRelaisController", "Amp LF"))
        self.groupBox_17.setTitle(_translate("ReverbChamberRelaisController", "SG"))
        self.groupBox_18.setTitle(_translate("ReverbChamberRelaisController", "PM FWD"))
        self.groupBox_19.setTitle(_translate("ReverbChamberRelaisController", "PM REV"))
        self.groupBox_20.setTitle(_translate("ReverbChamberRelaisController", "Switch 3"))
        self.RxSwitch_LF.setText(_translate("ReverbChamberRelaisController", "LogPer"))
        self.RxSwitch_HF.setText(_translate("ReverbChamberRelaisController", "Horn"))
        self.groupBox_27.setTitle(_translate("ReverbChamberRelaisController", "LogPer"))
        self.groupBox_28.setTitle(_translate("ReverbChamberRelaisController", "Amp LF"))
        self.groupBox_31.setTitle(_translate("ReverbChamberRelaisController", "Horn"))
        self.groupBox_32.setTitle(_translate("ReverbChamberRelaisController", "Amp LF"))
        self.groupBox_29.setTitle(_translate("ReverbChamberRelaisController", "Switch 4"))
        self.AttSwitch_On.setText(_translate("ReverbChamberRelaisController", "Att 20 dB"))
        self.AttSwitch_Off.setText(_translate("ReverbChamberRelaisController", "direct"))
        self.groupBox_30.setTitle(_translate("ReverbChamberRelaisController", "Att"))
        self.groupBox_33.setTitle(_translate("ReverbChamberRelaisController", "Switch 5"))
        self.RxSwitch_PM.setText(_translate("ReverbChamberRelaisController", "PM"))
        self.RxSwitch_Rec.setText(_translate("ReverbChamberRelaisController", "Rec"))
        self.groupBox_34.setTitle(_translate("ReverbChamberRelaisController", "PM Rx"))
        self.groupBox_35.setTitle(_translate("ReverbChamberRelaisController", "Rec"))
        self.pushButton.setText(_translate("ReverbChamberRelaisController", "Safe Setting"))
