# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RCSwitch.ui'
#
# Created: Wed May  5 13:06:14 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ReverbChamberRelaisController(object):
    def setupUi(self, ReverbChamberRelaisController):
        ReverbChamberRelaisController.setObjectName("ReverbChamberRelaisController")
        ReverbChamberRelaisController.resize(692, 494)
        self.centralwidget = QtGui.QWidget(ReverbChamberRelaisController)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 200, 111, 141))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 91, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sgSwitch_LF = QtGui.QRadioButton(self.layoutWidget)
        self.sgSwitch_LF.setEnabled(True)
        self.sgSwitch_LF.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.sgSwitch_LF.setChecked(False)
        self.sgSwitch_LF.setObjectName("sgSwitch_LF")
        self.verticalLayout.addWidget(self.sgSwitch_LF)
        self.sgSwitch_HF = QtGui.QRadioButton(self.layoutWidget)
        self.sgSwitch_HF.setEnabled(True)
        self.sgSwitch_HF.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.sgSwitch_HF.setObjectName("sgSwitch_HF")
        self.verticalLayout.addWidget(self.sgSwitch_HF)
        self.sgSwitch_Direct = QtGui.QRadioButton(self.layoutWidget)
        self.sgSwitch_Direct.setEnabled(True)
        self.sgSwitch_Direct.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.sgSwitch_Direct.setChecked(True)
        self.sgSwitch_Direct.setObjectName("sgSwitch_Direct")
        self.verticalLayout.addWidget(self.sgSwitch_Direct)
        self.conn_amp_lf = QtGui.QFrame(self.centralwidget)
        self.conn_amp_lf.setEnabled(False)
        self.conn_amp_lf.setGeometry(QtCore.QRect(170, 230, 231, 16))
        self.conn_amp_lf.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_lf.setLineWidth(2)
        self.conn_amp_lf.setFrameShape(QtGui.QFrame.HLine)
        self.conn_amp_lf.setObjectName("conn_amp_lf")
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(190, 209, 61, 41))
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 0, 61, 41))
        self.groupBox_4.setAutoFillBackground(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_5.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_5.setAutoFillBackground(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.conn_amp_hf = QtGui.QFrame(self.centralwidget)
        self.conn_amp_hf.setEnabled(False)
        self.conn_amp_hf.setGeometry(QtCore.QRect(170, 270, 231, 16))
        self.conn_amp_hf.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_hf.setLineWidth(2)
        self.conn_amp_hf.setFrameShape(QtGui.QFrame.HLine)
        self.conn_amp_hf.setObjectName("conn_amp_hf")
        self.conn_amp_direct = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct.setGeometry(QtCore.QRect(170, 300, 231, 16))
        self.conn_amp_direct.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct.setLineWidth(2)
        self.conn_amp_direct.setFrameShape(QtGui.QFrame.HLine)
        self.conn_amp_direct.setObjectName("conn_amp_direct")
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(190, 250, 61, 41))
        self.groupBox_3.setAutoFillBackground(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(400, 220, 31, 101))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.conn_amp_direct_2 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_2.setGeometry(QtCore.QRect(430, 270, 31, 16))
        self.conn_amp_direct_2.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_2.setLineWidth(2)
        self.conn_amp_direct_2.setFrameShape(QtGui.QFrame.HLine)
        self.conn_amp_direct_2.setObjectName("conn_amp_direct_2")
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(270, 210, 41, 41))
        self.groupBox_6.setAutoFillBackground(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_7.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_7.setAutoFillBackground(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.groupBox_8 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(330, 250, 41, 41))
        self.groupBox_8.setAutoFillBackground(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox_9.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_9.setAutoFillBackground(True)
        self.groupBox_9.setObjectName("groupBox_9")
        self.groupBox_10 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_10.setGeometry(QtCore.QRect(460, 200, 111, 141))
        self.groupBox_10.setFlat(False)
        self.groupBox_10.setCheckable(False)
        self.groupBox_10.setObjectName("groupBox_10")
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox_10)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 91, 111))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TxSwitch_LF = QtGui.QRadioButton(self.layoutWidget_2)
        self.TxSwitch_LF.setEnabled(True)
        self.TxSwitch_LF.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.TxSwitch_LF.setChecked(False)
        self.TxSwitch_LF.setObjectName("TxSwitch_LF")
        self.verticalLayout_2.addWidget(self.TxSwitch_LF)
        self.TxSwitch_HF = QtGui.QRadioButton(self.layoutWidget_2)
        self.TxSwitch_HF.setEnabled(True)
        self.TxSwitch_HF.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.TxSwitch_HF.setObjectName("TxSwitch_HF")
        self.verticalLayout_2.addWidget(self.TxSwitch_HF)
        self.TxSwitch_Term = QtGui.QRadioButton(self.layoutWidget_2)
        self.TxSwitch_Term.setEnabled(True)
        self.TxSwitch_Term.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.TxSwitch_Term.setChecked(True)
        self.TxSwitch_Term.setObjectName("TxSwitch_Term")
        self.verticalLayout_2.addWidget(self.TxSwitch_Term)
        self.conn_amp_direct_3 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_3.setEnabled(False)
        self.conn_amp_direct_3.setGeometry(QtCore.QRect(570, 230, 31, 16))
        self.conn_amp_direct_3.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_3.setLineWidth(2)
        self.conn_amp_direct_3.setFrameShape(QtGui.QFrame.HLine)
        self.conn_amp_direct_3.setObjectName("conn_amp_direct_3")
        self.conn_amp_direct_4 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_4.setEnabled(False)
        self.conn_amp_direct_4.setGeometry(QtCore.QRect(570, 270, 31, 16))
        self.conn_amp_direct_4.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_4.setLineWidth(2)
        self.conn_amp_direct_4.setFrameShape(QtGui.QFrame.HLine)
        self.conn_amp_direct_4.setObjectName("conn_amp_direct_4")
        self.conn_amp_direct_5 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_5.setGeometry(QtCore.QRect(570, 300, 31, 16))
        self.conn_amp_direct_5.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_5.setLineWidth(2)
        self.conn_amp_direct_5.setFrameShape(QtGui.QFrame.HLine)
        self.conn_amp_direct_5.setObjectName("conn_amp_direct_5")
        self.groupBox_11 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_11.setGeometry(QtCore.QRect(600, 220, 61, 31))
        self.groupBox_11.setAutoFillBackground(True)
        self.groupBox_11.setObjectName("groupBox_11")
        self.groupBox_12 = QtGui.QGroupBox(self.groupBox_11)
        self.groupBox_12.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_12.setAutoFillBackground(True)
        self.groupBox_12.setObjectName("groupBox_12")
        self.groupBox_21 = QtGui.QGroupBox(self.groupBox_11)
        self.groupBox_21.setGeometry(QtCore.QRect(0, 0, 61, 31))
        self.groupBox_21.setAutoFillBackground(True)
        self.groupBox_21.setObjectName("groupBox_21")
        self.groupBox_22 = QtGui.QGroupBox(self.groupBox_21)
        self.groupBox_22.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_22.setAutoFillBackground(True)
        self.groupBox_22.setObjectName("groupBox_22")
        self.groupBox_23 = QtGui.QGroupBox(self.groupBox_11)
        self.groupBox_23.setGeometry(QtCore.QRect(0, 70, 61, 31))
        self.groupBox_23.setAutoFillBackground(True)
        self.groupBox_23.setObjectName("groupBox_23")
        self.groupBox_24 = QtGui.QGroupBox(self.groupBox_23)
        self.groupBox_24.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_24.setAutoFillBackground(True)
        self.groupBox_24.setObjectName("groupBox_24")
        self.groupBox_25 = QtGui.QGroupBox(self.groupBox_11)
        self.groupBox_25.setGeometry(QtCore.QRect(0, 40, 61, 31))
        self.groupBox_25.setAutoFillBackground(True)
        self.groupBox_25.setObjectName("groupBox_25")
        self.groupBox_26 = QtGui.QGroupBox(self.groupBox_25)
        self.groupBox_26.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_26.setAutoFillBackground(True)
        self.groupBox_26.setObjectName("groupBox_26")
        self.groupBox_13 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_13.setGeometry(QtCore.QRect(600, 260, 61, 31))
        self.groupBox_13.setAutoFillBackground(True)
        self.groupBox_13.setObjectName("groupBox_13")
        self.groupBox_14 = QtGui.QGroupBox(self.groupBox_13)
        self.groupBox_14.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_14.setAutoFillBackground(True)
        self.groupBox_14.setObjectName("groupBox_14")
        self.groupBox_15 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_15.setGeometry(QtCore.QRect(600, 290, 61, 31))
        self.groupBox_15.setAutoFillBackground(True)
        self.groupBox_15.setObjectName("groupBox_15")
        self.groupBox_16 = QtGui.QGroupBox(self.groupBox_15)
        self.groupBox_16.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_16.setAutoFillBackground(True)
        self.groupBox_16.setObjectName("groupBox_16")
        self.groupBox_17 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_17.setGeometry(QtCore.QRect(10, 250, 31, 31))
        self.groupBox_17.setFlat(False)
        self.groupBox_17.setCheckable(False)
        self.groupBox_17.setObjectName("groupBox_17")
        self.conn_amp_direct_6 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_6.setGeometry(QtCore.QRect(40, 260, 21, 20))
        self.conn_amp_direct_6.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_6.setLineWidth(2)
        self.conn_amp_direct_6.setFrameShape(QtGui.QFrame.HLine)
        self.conn_amp_direct_6.setObjectName("conn_amp_direct_6")
        self.groupBox_18 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_18.setGeometry(QtCore.QRect(10, 70, 61, 31))
        self.groupBox_18.setFlat(False)
        self.groupBox_18.setCheckable(False)
        self.groupBox_18.setObjectName("groupBox_18")
        self.groupBox_19 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_19.setGeometry(QtCore.QRect(10, 110, 61, 31))
        self.groupBox_19.setFlat(False)
        self.groupBox_19.setCheckable(False)
        self.groupBox_19.setObjectName("groupBox_19")
        self.conn_amp_direct_7 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_7.setGeometry(QtCore.QRect(70, 120, 31, 16))
        self.conn_amp_direct_7.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_7.setLineWidth(2)
        self.conn_amp_direct_7.setFrameShape(QtGui.QFrame.HLine)
        self.conn_amp_direct_7.setObjectName("conn_amp_direct_7")
        self.conn_amp_direct_8 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_8.setGeometry(QtCore.QRect(70, 80, 31, 16))
        self.conn_amp_direct_8.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_8.setLineWidth(2)
        self.conn_amp_direct_8.setFrameShape(QtGui.QFrame.HLine)
        self.conn_amp_direct_8.setObjectName("conn_amp_direct_8")
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(100, 70, 31, 71))
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.conn_amp_direct_9 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_9.setEnabled(False)
        self.conn_amp_direct_9.setGeometry(QtCore.QRect(130, 70, 151, 16))
        self.conn_amp_direct_9.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_9.setLineWidth(2)
        self.conn_amp_direct_9.setFrameShape(QtGui.QFrame.HLine)
        self.conn_amp_direct_9.setObjectName("conn_amp_direct_9")
        self.conn_amp_direct_10 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_10.setEnabled(False)
        self.conn_amp_direct_10.setGeometry(QtCore.QRect(130, 80, 211, 16))
        self.conn_amp_direct_10.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_10.setLineWidth(2)
        self.conn_amp_direct_10.setFrameShape(QtGui.QFrame.HLine)
        self.conn_amp_direct_10.setObjectName("conn_amp_direct_10")
        self.conn_amp_direct_11 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_11.setEnabled(False)
        self.conn_amp_direct_11.setGeometry(QtCore.QRect(130, 110, 171, 16))
        self.conn_amp_direct_11.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_11.setLineWidth(2)
        self.conn_amp_direct_11.setFrameShape(QtGui.QFrame.HLine)
        self.conn_amp_direct_11.setObjectName("conn_amp_direct_11")
        self.conn_amp_direct_12 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_12.setEnabled(False)
        self.conn_amp_direct_12.setGeometry(QtCore.QRect(130, 120, 221, 16))
        self.conn_amp_direct_12.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_12.setLineWidth(2)
        self.conn_amp_direct_12.setFrameShape(QtGui.QFrame.HLine)
        self.conn_amp_direct_12.setObjectName("conn_amp_direct_12")
        self.conn_amp_direct_13 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_13.setEnabled(False)
        self.conn_amp_direct_13.setGeometry(QtCore.QRect(270, 80, 20, 141))
        self.conn_amp_direct_13.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_13.setLineWidth(2)
        self.conn_amp_direct_13.setFrameShape(QtGui.QFrame.VLine)
        self.conn_amp_direct_13.setObjectName("conn_amp_direct_13")
        self.conn_amp_direct_14 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_14.setEnabled(False)
        self.conn_amp_direct_14.setGeometry(QtCore.QRect(330, 90, 20, 171))
        self.conn_amp_direct_14.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_14.setLineWidth(2)
        self.conn_amp_direct_14.setFrameShape(QtGui.QFrame.VLine)
        self.conn_amp_direct_14.setObjectName("conn_amp_direct_14")
        self.conn_amp_direct_15 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_15.setEnabled(False)
        self.conn_amp_direct_15.setGeometry(QtCore.QRect(290, 120, 20, 101))
        self.conn_amp_direct_15.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_15.setLineWidth(2)
        self.conn_amp_direct_15.setFrameShape(QtGui.QFrame.VLine)
        self.conn_amp_direct_15.setObjectName("conn_amp_direct_15")
        self.conn_amp_direct_16 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_16.setEnabled(False)
        self.conn_amp_direct_16.setGeometry(QtCore.QRect(340, 130, 20, 131))
        self.conn_amp_direct_16.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_16.setLineWidth(2)
        self.conn_amp_direct_16.setFrameShape(QtGui.QFrame.VLine)
        self.conn_amp_direct_16.setObjectName("conn_amp_direct_16")
        self.conn_amp_direct_17 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_17.setGeometry(QtCore.QRect(430, 410, 31, 16))
        self.conn_amp_direct_17.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_17.setLineWidth(2)
        self.conn_amp_direct_17.setFrameShape(QtGui.QFrame.HLine)
        self.conn_amp_direct_17.setObjectName("conn_amp_direct_17")
        self.conn_amp_direct_18 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_18.setEnabled(True)
        self.conn_amp_direct_18.setGeometry(QtCore.QRect(570, 390, 31, 16))
        self.conn_amp_direct_18.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_18.setLineWidth(2)
        self.conn_amp_direct_18.setFrameShape(QtGui.QFrame.HLine)
        self.conn_amp_direct_18.setObjectName("conn_amp_direct_18")
        self.groupBox_20 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_20.setGeometry(QtCore.QRect(460, 360, 111, 101))
        self.groupBox_20.setFlat(False)
        self.groupBox_20.setCheckable(False)
        self.groupBox_20.setObjectName("groupBox_20")
        self.layoutWidget_3 = QtGui.QWidget(self.groupBox_20)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 20, 91, 71))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.RxSwitch_LF = QtGui.QRadioButton(self.layoutWidget_3)
        self.RxSwitch_LF.setEnabled(True)
        self.RxSwitch_LF.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.RxSwitch_LF.setChecked(True)
        self.RxSwitch_LF.setObjectName("RxSwitch_LF")
        self.verticalLayout_3.addWidget(self.RxSwitch_LF)
        self.RxSwitch_HF = QtGui.QRadioButton(self.layoutWidget_3)
        self.RxSwitch_HF.setEnabled(True)
        self.RxSwitch_HF.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.RxSwitch_HF.setObjectName("RxSwitch_HF")
        self.verticalLayout_3.addWidget(self.RxSwitch_HF)
        self.conn_amp_direct_19 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_19.setEnabled(False)
        self.conn_amp_direct_19.setGeometry(QtCore.QRect(570, 430, 31, 16))
        self.conn_amp_direct_19.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_19.setLineWidth(2)
        self.conn_amp_direct_19.setFrameShape(QtGui.QFrame.HLine)
        self.conn_amp_direct_19.setObjectName("conn_amp_direct_19")
        self.groupBox_27 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_27.setGeometry(QtCore.QRect(600, 370, 61, 31))
        self.groupBox_27.setAutoFillBackground(True)
        self.groupBox_27.setObjectName("groupBox_27")
        self.groupBox_28 = QtGui.QGroupBox(self.groupBox_27)
        self.groupBox_28.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_28.setAutoFillBackground(True)
        self.groupBox_28.setObjectName("groupBox_28")
        self.groupBox_31 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_31.setGeometry(QtCore.QRect(600, 410, 61, 31))
        self.groupBox_31.setAutoFillBackground(True)
        self.groupBox_31.setObjectName("groupBox_31")
        self.groupBox_32 = QtGui.QGroupBox(self.groupBox_31)
        self.groupBox_32.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.groupBox_32.setAutoFillBackground(True)
        self.groupBox_32.setObjectName("groupBox_32")
        self.conn_amp_direct_20 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_20.setEnabled(True)
        self.conn_amp_direct_20.setGeometry(QtCore.QRect(240, 390, 81, 20))
        self.conn_amp_direct_20.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_20.setLineWidth(2)
        self.conn_amp_direct_20.setFrameShape(QtGui.QFrame.HLine)
        self.conn_amp_direct_20.setObjectName("conn_amp_direct_20")
        self.conn_amp_direct_21 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_21.setEnabled(False)
        self.conn_amp_direct_21.setGeometry(QtCore.QRect(240, 420, 81, 20))
        self.conn_amp_direct_21.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_21.setLineWidth(2)
        self.conn_amp_direct_21.setFrameShape(QtGui.QFrame.HLine)
        self.conn_amp_direct_21.setObjectName("conn_amp_direct_21")
        self.groupBox_29 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_29.setGeometry(QtCore.QRect(320, 360, 111, 101))
        self.groupBox_29.setFlat(False)
        self.groupBox_29.setCheckable(False)
        self.groupBox_29.setObjectName("groupBox_29")
        self.layoutWidget_4 = QtGui.QWidget(self.groupBox_29)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 20, 91, 71))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.AttSwitch_On = QtGui.QRadioButton(self.layoutWidget_4)
        self.AttSwitch_On.setEnabled(True)
        self.AttSwitch_On.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AttSwitch_On.setChecked(True)
        self.AttSwitch_On.setObjectName("AttSwitch_On")
        self.verticalLayout_4.addWidget(self.AttSwitch_On)
        self.AttSwitch_Off = QtGui.QRadioButton(self.layoutWidget_4)
        self.AttSwitch_Off.setEnabled(True)
        self.AttSwitch_Off.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AttSwitch_Off.setObjectName("AttSwitch_Off")
        self.verticalLayout_4.addWidget(self.AttSwitch_Off)
        self.conn_amp_direct_22 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_22.setGeometry(QtCore.QRect(180, 410, 31, 16))
        self.conn_amp_direct_22.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_22.setLineWidth(2)
        self.conn_amp_direct_22.setFrameShape(QtGui.QFrame.HLine)
        self.conn_amp_direct_22.setObjectName("conn_amp_direct_22")
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(210, 390, 31, 51))
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.groupBox_30 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_30.setGeometry(QtCore.QRect(260, 370, 41, 41))
        self.groupBox_30.setAutoFillBackground(True)
        self.groupBox_30.setObjectName("groupBox_30")
        self.conn_amp_direct_23 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_23.setEnabled(False)
        self.conn_amp_direct_23.setGeometry(QtCore.QRect(81, 420, 20, 20))
        self.conn_amp_direct_23.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_23.setLineWidth(2)
        self.conn_amp_direct_23.setFrameShape(QtGui.QFrame.HLine)
        self.conn_amp_direct_23.setObjectName("conn_amp_direct_23")
        self.groupBox_33 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_33.setGeometry(QtCore.QRect(100, 360, 81, 101))
        self.groupBox_33.setFlat(False)
        self.groupBox_33.setCheckable(False)
        self.groupBox_33.setObjectName("groupBox_33")
        self.layoutWidget_5 = QtGui.QWidget(self.groupBox_33)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 20, 61, 71))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.RxSwitch_PM = QtGui.QRadioButton(self.layoutWidget_5)
        self.RxSwitch_PM.setEnabled(True)
        self.RxSwitch_PM.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.RxSwitch_PM.setChecked(True)
        self.RxSwitch_PM.setObjectName("RxSwitch_PM")
        self.verticalLayout_5.addWidget(self.RxSwitch_PM)
        self.RxSwitch_Rec = QtGui.QRadioButton(self.layoutWidget_5)
        self.RxSwitch_Rec.setEnabled(True)
        self.RxSwitch_Rec.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.RxSwitch_Rec.setObjectName("RxSwitch_Rec")
        self.verticalLayout_5.addWidget(self.RxSwitch_Rec)
        self.conn_amp_direct_25 = QtGui.QFrame(self.centralwidget)
        self.conn_amp_direct_25.setEnabled(True)
        self.conn_amp_direct_25.setGeometry(QtCore.QRect(80, 390, 21, 20))
        self.conn_amp_direct_25.setFrameShadow(QtGui.QFrame.Plain)
        self.conn_amp_direct_25.setLineWidth(2)
        self.conn_amp_direct_25.setFrameShape(QtGui.QFrame.HLine)
        self.conn_amp_direct_25.setObjectName("conn_amp_direct_25")
        self.groupBox_34 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_34.setGeometry(QtCore.QRect(30, 380, 51, 31))
        self.groupBox_34.setFlat(False)
        self.groupBox_34.setCheckable(False)
        self.groupBox_34.setObjectName("groupBox_34")
        self.groupBox_35 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_35.setGeometry(QtCore.QRect(30, 410, 51, 31))
        self.groupBox_35.setFlat(False)
        self.groupBox_35.setCheckable(False)
        self.groupBox_35.setObjectName("groupBox_35")
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(440, 20, 161, 71))
        self.pushButton.setObjectName("pushButton")
        ReverbChamberRelaisController.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(ReverbChamberRelaisController)
        self.statusbar.setObjectName("statusbar")
        ReverbChamberRelaisController.setStatusBar(self.statusbar)

        self.retranslateUi(ReverbChamberRelaisController)
        QtCore.QObject.connect(self.sgSwitch_Direct, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct.setEnabled)
        QtCore.QObject.connect(self.sgSwitch_HF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_hf.setEnabled)
        QtCore.QObject.connect(self.sgSwitch_LF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_lf.setEnabled)
        QtCore.QObject.connect(self.sgSwitch_HF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_14.setEnabled)
        QtCore.QObject.connect(self.sgSwitch_HF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_16.setEnabled)
        QtCore.QObject.connect(self.sgSwitch_LF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_13.setEnabled)
        QtCore.QObject.connect(self.sgSwitch_LF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_15.setEnabled)
        QtCore.QObject.connect(self.sgSwitch_LF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_11.setEnabled)
        QtCore.QObject.connect(self.sgSwitch_LF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_9.setEnabled)
        QtCore.QObject.connect(self.sgSwitch_HF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_10.setEnabled)
        QtCore.QObject.connect(self.sgSwitch_HF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_12.setEnabled)
        QtCore.QObject.connect(self.TxSwitch_Term, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_5.setEnabled)
        QtCore.QObject.connect(self.TxSwitch_HF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_4.setEnabled)
        QtCore.QObject.connect(self.TxSwitch_LF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_3.setEnabled)
        QtCore.QObject.connect(self.RxSwitch_LF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_18.setEnabled)
        QtCore.QObject.connect(self.RxSwitch_HF, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_19.setEnabled)
        QtCore.QObject.connect(self.AttSwitch_On, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_20.setEnabled)
        QtCore.QObject.connect(self.AttSwitch_Off, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_21.setEnabled)
        QtCore.QObject.connect(self.RxSwitch_PM, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_25.setEnabled)
        QtCore.QObject.connect(self.RxSwitch_Rec, QtCore.SIGNAL("toggled(bool)"), self.conn_amp_direct_23.setEnabled)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), self.TxSwitch_Term.click)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), self.sgSwitch_Direct.click)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), self.AttSwitch_On.click)
        QtCore.QMetaObject.connectSlotsByName(ReverbChamberRelaisController)

    def retranslateUi(self, ReverbChamberRelaisController):
        ReverbChamberRelaisController.setWindowTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Reverb Chamber Matrix Switch Controller ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Switch 1", None, QtGui.QApplication.UnicodeUTF8))
        self.sgSwitch_LF.setText(QtGui.QApplication.translate("ReverbChamberRelaisController", "LF", None, QtGui.QApplication.UnicodeUTF8))
        self.sgSwitch_HF.setText(QtGui.QApplication.translate("ReverbChamberRelaisController", "HF", None, QtGui.QApplication.UnicodeUTF8))
        self.sgSwitch_Direct.setText(QtGui.QApplication.translate("ReverbChamberRelaisController", "Direct", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Amp LF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Amp LF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Amp LF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Amp HF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "DC LF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Amp LF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "DC HF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Amp LF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Switch 2", None, QtGui.QApplication.UnicodeUTF8))
        self.TxSwitch_LF.setText(QtGui.QApplication.translate("ReverbChamberRelaisController", "LogPer", None, QtGui.QApplication.UnicodeUTF8))
        self.TxSwitch_HF.setText(QtGui.QApplication.translate("ReverbChamberRelaisController", "Horn", None, QtGui.QApplication.UnicodeUTF8))
        self.TxSwitch_Term.setText(QtGui.QApplication.translate("ReverbChamberRelaisController", "Term", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_11.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "LogPer", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_12.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Amp LF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_21.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "LogPer", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_22.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Amp LF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_23.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Term", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_24.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Amp LF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_25.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Horn", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_26.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Amp LF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_13.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Horn", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_14.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Amp LF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_15.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Term", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_16.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Amp LF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_17.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "SG", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_18.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "PM FWD", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_19.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "PM REV", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_20.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Switch 3", None, QtGui.QApplication.UnicodeUTF8))
        self.RxSwitch_LF.setText(QtGui.QApplication.translate("ReverbChamberRelaisController", "LogPer", None, QtGui.QApplication.UnicodeUTF8))
        self.RxSwitch_HF.setText(QtGui.QApplication.translate("ReverbChamberRelaisController", "Horn", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_27.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "LogPer", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_28.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Amp LF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_31.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Horn", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_32.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Amp LF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_29.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Switch 4", None, QtGui.QApplication.UnicodeUTF8))
        self.AttSwitch_On.setText(QtGui.QApplication.translate("ReverbChamberRelaisController", "Att 20 dB", None, QtGui.QApplication.UnicodeUTF8))
        self.AttSwitch_Off.setText(QtGui.QApplication.translate("ReverbChamberRelaisController", "direct", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_30.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Att", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_33.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Switch 5", None, QtGui.QApplication.UnicodeUTF8))
        self.RxSwitch_PM.setText(QtGui.QApplication.translate("ReverbChamberRelaisController", "PM", None, QtGui.QApplication.UnicodeUTF8))
        self.RxSwitch_Rec.setText(QtGui.QApplication.translate("ReverbChamberRelaisController", "Rec", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_34.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "PM Rx", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_35.setTitle(QtGui.QApplication.translate("ReverbChamberRelaisController", "Rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("ReverbChamberRelaisController", "Safe Setting", None, QtGui.QApplication.UnicodeUTF8))

