# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'RCSwitch.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGroupBox, QMainWindow,
    QPushButton, QRadioButton, QSizePolicy, QStatusBar,
    QVBoxLayout, QWidget)

class Ui_ReverbChamberRelaisController(object):
    def setupUi(self, ReverbChamberRelaisController):
        if not ReverbChamberRelaisController.objectName():
            ReverbChamberRelaisController.setObjectName(u"ReverbChamberRelaisController")
        ReverbChamberRelaisController.resize(692, 494)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ReverbChamberRelaisController.sizePolicy().hasHeightForWidth())
        ReverbChamberRelaisController.setSizePolicy(sizePolicy)
        ReverbChamberRelaisController.setMinimumSize(QSize(692, 494))
        ReverbChamberRelaisController.setMaximumSize(QSize(692, 494))
        ReverbChamberRelaisController.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.centralwidget = QWidget(ReverbChamberRelaisController)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(60, 200, 111, 141))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.layoutWidget = QWidget(self.groupBox)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 20, 91, 111))
        self.verticalLayout = QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.sgSwitch_LF = QRadioButton(self.layoutWidget)
        self.sgSwitch_LF.setObjectName(u"sgSwitch_LF")
        self.sgSwitch_LF.setEnabled(True)
        self.sgSwitch_LF.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.sgSwitch_LF.setChecked(False)

        self.verticalLayout.addWidget(self.sgSwitch_LF)

        self.sgSwitch_HF = QRadioButton(self.layoutWidget)
        self.sgSwitch_HF.setObjectName(u"sgSwitch_HF")
        self.sgSwitch_HF.setEnabled(True)
        self.sgSwitch_HF.setLayoutDirection(Qt.LayoutDirection.RightToLeft)

        self.verticalLayout.addWidget(self.sgSwitch_HF)

        self.sgSwitch_Direct = QRadioButton(self.layoutWidget)
        self.sgSwitch_Direct.setObjectName(u"sgSwitch_Direct")
        self.sgSwitch_Direct.setEnabled(True)
        self.sgSwitch_Direct.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.sgSwitch_Direct.setChecked(True)

        self.verticalLayout.addWidget(self.sgSwitch_Direct)

        self.conn_amp_lf = QFrame(self.centralwidget)
        self.conn_amp_lf.setObjectName(u"conn_amp_lf")
        self.conn_amp_lf.setEnabled(False)
        self.conn_amp_lf.setGeometry(QRect(170, 230, 231, 16))
        self.conn_amp_lf.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_lf.setLineWidth(2)
        self.conn_amp_lf.setFrameShape(QFrame.Shape.HLine)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(190, 209, 61, 41))
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_4 = QGroupBox(self.groupBox_2)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(0, 0, 61, 41))
        self.groupBox_4.setAutoFillBackground(True)
        self.groupBox_5 = QGroupBox(self.groupBox_4)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(30, 40, 61, 41))
        self.groupBox_5.setAutoFillBackground(True)
        self.conn_amp_hf = QFrame(self.centralwidget)
        self.conn_amp_hf.setObjectName(u"conn_amp_hf")
        self.conn_amp_hf.setEnabled(False)
        self.conn_amp_hf.setGeometry(QRect(170, 270, 231, 16))
        self.conn_amp_hf.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_hf.setLineWidth(2)
        self.conn_amp_hf.setFrameShape(QFrame.Shape.HLine)
        self.conn_amp_direct = QFrame(self.centralwidget)
        self.conn_amp_direct.setObjectName(u"conn_amp_direct")
        self.conn_amp_direct.setGeometry(QRect(170, 300, 231, 16))
        self.conn_amp_direct.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct.setLineWidth(2)
        self.conn_amp_direct.setFrameShape(QFrame.Shape.HLine)
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(190, 250, 61, 41))
        self.groupBox_3.setAutoFillBackground(True)
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(400, 220, 31, 101))
        self.frame.setStyleSheet(u"color: black;")
        self.frame.setFrameShape(QFrame.Shape.Box)
        self.frame.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct_2 = QFrame(self.centralwidget)
        self.conn_amp_direct_2.setObjectName(u"conn_amp_direct_2")
        self.conn_amp_direct_2.setGeometry(QRect(430, 270, 31, 16))
        self.conn_amp_direct_2.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct_2.setLineWidth(2)
        self.conn_amp_direct_2.setFrameShape(QFrame.Shape.HLine)
        self.groupBox_6 = QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(270, 210, 41, 41))
        self.groupBox_6.setAutoFillBackground(True)
        self.groupBox_7 = QGroupBox(self.groupBox_6)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(30, 40, 61, 41))
        self.groupBox_7.setAutoFillBackground(True)
        self.groupBox_8 = QGroupBox(self.centralwidget)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(330, 250, 41, 41))
        self.groupBox_8.setAutoFillBackground(True)
        self.groupBox_9 = QGroupBox(self.groupBox_8)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(30, 40, 61, 41))
        self.groupBox_9.setAutoFillBackground(True)
        self.groupBox_10 = QGroupBox(self.centralwidget)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(460, 200, 111, 141))
        self.groupBox_10.setFlat(False)
        self.groupBox_10.setCheckable(False)
        self.layoutWidget_2 = QWidget(self.groupBox_10)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(10, 20, 91, 111))
        self.verticalLayout_2 = QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.TxSwitch_LF = QRadioButton(self.layoutWidget_2)
        self.TxSwitch_LF.setObjectName(u"TxSwitch_LF")
        self.TxSwitch_LF.setEnabled(True)
        self.TxSwitch_LF.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.TxSwitch_LF.setChecked(False)

        self.verticalLayout_2.addWidget(self.TxSwitch_LF)

        self.TxSwitch_HF = QRadioButton(self.layoutWidget_2)
        self.TxSwitch_HF.setObjectName(u"TxSwitch_HF")
        self.TxSwitch_HF.setEnabled(True)
        self.TxSwitch_HF.setLayoutDirection(Qt.LayoutDirection.RightToLeft)

        self.verticalLayout_2.addWidget(self.TxSwitch_HF)

        self.TxSwitch_Term = QRadioButton(self.layoutWidget_2)
        self.TxSwitch_Term.setObjectName(u"TxSwitch_Term")
        self.TxSwitch_Term.setEnabled(True)
        self.TxSwitch_Term.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.TxSwitch_Term.setChecked(True)

        self.verticalLayout_2.addWidget(self.TxSwitch_Term)

        self.conn_amp_direct_3 = QFrame(self.centralwidget)
        self.conn_amp_direct_3.setObjectName(u"conn_amp_direct_3")
        self.conn_amp_direct_3.setEnabled(False)
        self.conn_amp_direct_3.setGeometry(QRect(570, 230, 31, 16))
        self.conn_amp_direct_3.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct_3.setLineWidth(2)
        self.conn_amp_direct_3.setFrameShape(QFrame.Shape.HLine)
        self.conn_amp_direct_4 = QFrame(self.centralwidget)
        self.conn_amp_direct_4.setObjectName(u"conn_amp_direct_4")
        self.conn_amp_direct_4.setEnabled(False)
        self.conn_amp_direct_4.setGeometry(QRect(570, 264, 31, 16))
        self.conn_amp_direct_4.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct_4.setLineWidth(2)
        self.conn_amp_direct_4.setFrameShape(QFrame.Shape.HLine)
        self.conn_amp_direct_5 = QFrame(self.centralwidget)
        self.conn_amp_direct_5.setObjectName(u"conn_amp_direct_5")
        self.conn_amp_direct_5.setGeometry(QRect(570, 300, 31, 16))
        self.conn_amp_direct_5.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct_5.setLineWidth(2)
        self.conn_amp_direct_5.setFrameShape(QFrame.Shape.HLine)
        self.groupBox_11 = QGroupBox(self.centralwidget)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(600, 215, 61, 31))
        self.groupBox_11.setAutoFillBackground(True)
        self.groupBox_12 = QGroupBox(self.groupBox_11)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(30, 40, 61, 41))
        self.groupBox_12.setAutoFillBackground(True)
        self.groupBox_23 = QGroupBox(self.groupBox_11)
        self.groupBox_23.setObjectName(u"groupBox_23")
        self.groupBox_23.setGeometry(QRect(0, 70, 61, 31))
        self.groupBox_23.setAutoFillBackground(True)
        self.groupBox_24 = QGroupBox(self.groupBox_23)
        self.groupBox_24.setObjectName(u"groupBox_24")
        self.groupBox_24.setGeometry(QRect(30, 40, 61, 41))
        self.groupBox_24.setAutoFillBackground(True)
        self.groupBox_25 = QGroupBox(self.groupBox_11)
        self.groupBox_25.setObjectName(u"groupBox_25")
        self.groupBox_25.setGeometry(QRect(0, 40, 61, 31))
        self.groupBox_25.setAutoFillBackground(True)
        self.groupBox_26 = QGroupBox(self.groupBox_25)
        self.groupBox_26.setObjectName(u"groupBox_26")
        self.groupBox_26.setGeometry(QRect(30, 40, 61, 41))
        self.groupBox_26.setAutoFillBackground(True)
        self.groupBox_13 = QGroupBox(self.centralwidget)
        self.groupBox_13.setObjectName(u"groupBox_13")
        self.groupBox_13.setGeometry(QRect(600, 250, 61, 31))
        self.groupBox_13.setAutoFillBackground(True)
        self.groupBox_14 = QGroupBox(self.groupBox_13)
        self.groupBox_14.setObjectName(u"groupBox_14")
        self.groupBox_14.setGeometry(QRect(30, 40, 61, 41))
        self.groupBox_14.setAutoFillBackground(True)
        self.groupBox_15 = QGroupBox(self.centralwidget)
        self.groupBox_15.setObjectName(u"groupBox_15")
        self.groupBox_15.setGeometry(QRect(600, 285, 61, 31))
        self.groupBox_15.setAutoFillBackground(True)
        self.groupBox_16 = QGroupBox(self.groupBox_15)
        self.groupBox_16.setObjectName(u"groupBox_16")
        self.groupBox_16.setGeometry(QRect(30, 40, 61, 41))
        self.groupBox_16.setAutoFillBackground(True)
        self.groupBox_17 = QGroupBox(self.centralwidget)
        self.groupBox_17.setObjectName(u"groupBox_17")
        self.groupBox_17.setGeometry(QRect(10, 247, 31, 31))
        self.groupBox_17.setFlat(False)
        self.groupBox_17.setCheckable(False)
        self.conn_amp_direct_6 = QFrame(self.centralwidget)
        self.conn_amp_direct_6.setObjectName(u"conn_amp_direct_6")
        self.conn_amp_direct_6.setGeometry(QRect(40, 260, 21, 20))
        self.conn_amp_direct_6.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct_6.setLineWidth(2)
        self.conn_amp_direct_6.setFrameShape(QFrame.Shape.HLine)
        self.groupBox_18 = QGroupBox(self.centralwidget)
        self.groupBox_18.setObjectName(u"groupBox_18")
        self.groupBox_18.setGeometry(QRect(10, 66, 61, 31))
        self.groupBox_18.setFlat(False)
        self.groupBox_18.setCheckable(False)
        self.groupBox_19 = QGroupBox(self.centralwidget)
        self.groupBox_19.setObjectName(u"groupBox_19")
        self.groupBox_19.setGeometry(QRect(10, 107, 61, 31))
        self.groupBox_19.setFlat(False)
        self.groupBox_19.setCheckable(False)
        self.conn_amp_direct_7 = QFrame(self.centralwidget)
        self.conn_amp_direct_7.setObjectName(u"conn_amp_direct_7")
        self.conn_amp_direct_7.setEnabled(False)
        self.conn_amp_direct_7.setGeometry(QRect(70, 120, 31, 16))
        self.conn_amp_direct_7.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct_7.setLineWidth(2)
        self.conn_amp_direct_7.setFrameShape(QFrame.Shape.HLine)
        self.conn_amp_direct_8 = QFrame(self.centralwidget)
        self.conn_amp_direct_8.setObjectName(u"conn_amp_direct_8")
        self.conn_amp_direct_8.setEnabled(False)
        self.conn_amp_direct_8.setGeometry(QRect(70, 80, 31, 16))
        self.conn_amp_direct_8.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct_8.setLineWidth(2)
        self.conn_amp_direct_8.setFrameShape(QFrame.Shape.HLine)
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(100, 70, 31, 71))
        self.frame_2.setStyleSheet(u"color: black;")
        self.frame_2.setFrameShape(QFrame.Shape.Box)
        self.frame_2.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct_9 = QFrame(self.centralwidget)
        self.conn_amp_direct_9.setObjectName(u"conn_amp_direct_9")
        self.conn_amp_direct_9.setEnabled(False)
        self.conn_amp_direct_9.setGeometry(QRect(130, 70, 151, 16))
        self.conn_amp_direct_9.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct_9.setLineWidth(2)
        self.conn_amp_direct_9.setFrameShape(QFrame.Shape.HLine)
        self.conn_amp_direct_10 = QFrame(self.centralwidget)
        self.conn_amp_direct_10.setObjectName(u"conn_amp_direct_10")
        self.conn_amp_direct_10.setEnabled(False)
        self.conn_amp_direct_10.setGeometry(QRect(130, 80, 211, 16))
        self.conn_amp_direct_10.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct_10.setLineWidth(2)
        self.conn_amp_direct_10.setFrameShape(QFrame.Shape.HLine)
        self.conn_amp_direct_11 = QFrame(self.centralwidget)
        self.conn_amp_direct_11.setObjectName(u"conn_amp_direct_11")
        self.conn_amp_direct_11.setEnabled(False)
        self.conn_amp_direct_11.setGeometry(QRect(130, 110, 171, 16))
        self.conn_amp_direct_11.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct_11.setLineWidth(2)
        self.conn_amp_direct_11.setFrameShape(QFrame.Shape.HLine)
        self.conn_amp_direct_12 = QFrame(self.centralwidget)
        self.conn_amp_direct_12.setObjectName(u"conn_amp_direct_12")
        self.conn_amp_direct_12.setEnabled(False)
        self.conn_amp_direct_12.setGeometry(QRect(130, 120, 230, 16))
        self.conn_amp_direct_12.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct_12.setLineWidth(2)
        self.conn_amp_direct_12.setFrameShape(QFrame.Shape.HLine)
        self.conn_amp_direct_13 = QFrame(self.centralwidget)
        self.conn_amp_direct_13.setObjectName(u"conn_amp_direct_13")
        self.conn_amp_direct_13.setEnabled(False)
        self.conn_amp_direct_13.setGeometry(QRect(270, 77, 20, 150))
        self.conn_amp_direct_13.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct_13.setLineWidth(2)
        self.conn_amp_direct_13.setFrameShape(QFrame.Shape.VLine)
        self.conn_amp_direct_14 = QFrame(self.centralwidget)
        self.conn_amp_direct_14.setObjectName(u"conn_amp_direct_14")
        self.conn_amp_direct_14.setEnabled(False)
        self.conn_amp_direct_14.setGeometry(QRect(330, 88, 20, 180))
        self.conn_amp_direct_14.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct_14.setLineWidth(2)
        self.conn_amp_direct_14.setFrameShape(QFrame.Shape.VLine)
        self.conn_amp_direct_15 = QFrame(self.centralwidget)
        self.conn_amp_direct_15.setObjectName(u"conn_amp_direct_15")
        self.conn_amp_direct_15.setEnabled(False)
        self.conn_amp_direct_15.setGeometry(QRect(290, 118, 20, 110))
        self.conn_amp_direct_15.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct_15.setLineWidth(2)
        self.conn_amp_direct_15.setFrameShape(QFrame.Shape.VLine)
        self.conn_amp_direct_16 = QFrame(self.centralwidget)
        self.conn_amp_direct_16.setObjectName(u"conn_amp_direct_16")
        self.conn_amp_direct_16.setEnabled(False)
        self.conn_amp_direct_16.setGeometry(QRect(350, 128, 20, 140))
        self.conn_amp_direct_16.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct_16.setLineWidth(2)
        self.conn_amp_direct_16.setFrameShape(QFrame.Shape.VLine)
        self.conn_amp_direct_17 = QFrame(self.centralwidget)
        self.conn_amp_direct_17.setObjectName(u"conn_amp_direct_17")
        self.conn_amp_direct_17.setGeometry(QRect(430, 410, 31, 16))
        self.conn_amp_direct_17.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct_17.setLineWidth(2)
        self.conn_amp_direct_17.setFrameShape(QFrame.Shape.HLine)
        self.conn_amp_direct_18 = QFrame(self.centralwidget)
        self.conn_amp_direct_18.setObjectName(u"conn_amp_direct_18")
        self.conn_amp_direct_18.setEnabled(True)
        self.conn_amp_direct_18.setGeometry(QRect(570, 390, 31, 16))
        self.conn_amp_direct_18.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct_18.setLineWidth(2)
        self.conn_amp_direct_18.setFrameShape(QFrame.Shape.HLine)
        self.groupBox_20 = QGroupBox(self.centralwidget)
        self.groupBox_20.setObjectName(u"groupBox_20")
        self.groupBox_20.setGeometry(QRect(460, 360, 111, 101))
        self.groupBox_20.setFlat(False)
        self.groupBox_20.setCheckable(False)
        self.layoutWidget_3 = QWidget(self.groupBox_20)
        self.layoutWidget_3.setObjectName(u"layoutWidget_3")
        self.layoutWidget_3.setGeometry(QRect(10, 20, 91, 71))
        self.verticalLayout_3 = QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.RxSwitch_LF = QRadioButton(self.layoutWidget_3)
        self.RxSwitch_LF.setObjectName(u"RxSwitch_LF")
        self.RxSwitch_LF.setEnabled(True)
        self.RxSwitch_LF.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.RxSwitch_LF.setChecked(True)

        self.verticalLayout_3.addWidget(self.RxSwitch_LF)

        self.RxSwitch_HF = QRadioButton(self.layoutWidget_3)
        self.RxSwitch_HF.setObjectName(u"RxSwitch_HF")
        self.RxSwitch_HF.setEnabled(True)
        self.RxSwitch_HF.setLayoutDirection(Qt.LayoutDirection.RightToLeft)

        self.verticalLayout_3.addWidget(self.RxSwitch_HF)

        self.conn_amp_direct_19 = QFrame(self.centralwidget)
        self.conn_amp_direct_19.setObjectName(u"conn_amp_direct_19")
        self.conn_amp_direct_19.setEnabled(False)
        self.conn_amp_direct_19.setGeometry(QRect(570, 430, 31, 16))
        self.conn_amp_direct_19.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct_19.setLineWidth(2)
        self.conn_amp_direct_19.setFrameShape(QFrame.Shape.HLine)
        self.groupBox_27 = QGroupBox(self.centralwidget)
        self.groupBox_27.setObjectName(u"groupBox_27")
        self.groupBox_27.setGeometry(QRect(600, 374, 61, 31))
        self.groupBox_27.setAutoFillBackground(True)
        self.groupBox_28 = QGroupBox(self.groupBox_27)
        self.groupBox_28.setObjectName(u"groupBox_28")
        self.groupBox_28.setGeometry(QRect(30, 40, 61, 41))
        self.groupBox_28.setAutoFillBackground(True)
        self.groupBox_31 = QGroupBox(self.centralwidget)
        self.groupBox_31.setObjectName(u"groupBox_31")
        self.groupBox_31.setGeometry(QRect(600, 413, 61, 31))
        self.groupBox_31.setAutoFillBackground(True)
        self.groupBox_32 = QGroupBox(self.groupBox_31)
        self.groupBox_32.setObjectName(u"groupBox_32")
        self.groupBox_32.setGeometry(QRect(30, 40, 61, 41))
        self.groupBox_32.setAutoFillBackground(True)
        self.conn_amp_direct_20 = QFrame(self.centralwidget)
        self.conn_amp_direct_20.setObjectName(u"conn_amp_direct_20")
        self.conn_amp_direct_20.setEnabled(True)
        self.conn_amp_direct_20.setGeometry(QRect(240, 390, 81, 20))
        self.conn_amp_direct_20.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct_20.setLineWidth(2)
        self.conn_amp_direct_20.setFrameShape(QFrame.Shape.HLine)
        self.conn_amp_direct_21 = QFrame(self.centralwidget)
        self.conn_amp_direct_21.setObjectName(u"conn_amp_direct_21")
        self.conn_amp_direct_21.setEnabled(False)
        self.conn_amp_direct_21.setGeometry(QRect(240, 420, 81, 20))
        self.conn_amp_direct_21.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct_21.setLineWidth(2)
        self.conn_amp_direct_21.setFrameShape(QFrame.Shape.HLine)
        self.groupBox_29 = QGroupBox(self.centralwidget)
        self.groupBox_29.setObjectName(u"groupBox_29")
        self.groupBox_29.setGeometry(QRect(320, 360, 111, 101))
        self.groupBox_29.setFlat(False)
        self.groupBox_29.setCheckable(False)
        self.layoutWidget_4 = QWidget(self.groupBox_29)
        self.layoutWidget_4.setObjectName(u"layoutWidget_4")
        self.layoutWidget_4.setGeometry(QRect(10, 20, 92, 71))
        self.verticalLayout_4 = QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.AttSwitch_On = QRadioButton(self.layoutWidget_4)
        self.AttSwitch_On.setObjectName(u"AttSwitch_On")
        self.AttSwitch_On.setEnabled(True)
        self.AttSwitch_On.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.AttSwitch_On.setChecked(True)

        self.verticalLayout_4.addWidget(self.AttSwitch_On)

        self.AttSwitch_Off = QRadioButton(self.layoutWidget_4)
        self.AttSwitch_Off.setObjectName(u"AttSwitch_Off")
        self.AttSwitch_Off.setEnabled(True)
        self.AttSwitch_Off.setLayoutDirection(Qt.LayoutDirection.RightToLeft)

        self.verticalLayout_4.addWidget(self.AttSwitch_Off)

        self.conn_amp_direct_22 = QFrame(self.centralwidget)
        self.conn_amp_direct_22.setObjectName(u"conn_amp_direct_22")
        self.conn_amp_direct_22.setGeometry(QRect(180, 410, 31, 16))
        self.conn_amp_direct_22.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct_22.setLineWidth(2)
        self.conn_amp_direct_22.setFrameShape(QFrame.Shape.HLine)
        self.frame_3 = QFrame(self.centralwidget)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(210, 390, 31, 51))
        self.frame_3.setStyleSheet(u"color: black;")
        self.frame_3.setFrameShape(QFrame.Shape.Box)
        self.frame_3.setFrameShadow(QFrame.Shadow.Plain)
        self.groupBox_30 = QGroupBox(self.centralwidget)
        self.groupBox_30.setObjectName(u"groupBox_30")
        self.groupBox_30.setGeometry(QRect(260, 370, 41, 41))
        self.groupBox_30.setAutoFillBackground(True)
        self.conn_amp_direct_23 = QFrame(self.centralwidget)
        self.conn_amp_direct_23.setObjectName(u"conn_amp_direct_23")
        self.conn_amp_direct_23.setEnabled(False)
        self.conn_amp_direct_23.setGeometry(QRect(81, 420, 20, 20))
        self.conn_amp_direct_23.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct_23.setLineWidth(2)
        self.conn_amp_direct_23.setFrameShape(QFrame.Shape.HLine)
        self.groupBox_33 = QGroupBox(self.centralwidget)
        self.groupBox_33.setObjectName(u"groupBox_33")
        self.groupBox_33.setGeometry(QRect(100, 360, 81, 101))
        self.groupBox_33.setFlat(False)
        self.groupBox_33.setCheckable(False)
        self.layoutWidget_5 = QWidget(self.groupBox_33)
        self.layoutWidget_5.setObjectName(u"layoutWidget_5")
        self.layoutWidget_5.setGeometry(QRect(10, 20, 61, 71))
        self.verticalLayout_5 = QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.RxSwitch_PM = QRadioButton(self.layoutWidget_5)
        self.RxSwitch_PM.setObjectName(u"RxSwitch_PM")
        self.RxSwitch_PM.setEnabled(True)
        self.RxSwitch_PM.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.RxSwitch_PM.setChecked(True)

        self.verticalLayout_5.addWidget(self.RxSwitch_PM)

        self.RxSwitch_Rec = QRadioButton(self.layoutWidget_5)
        self.RxSwitch_Rec.setObjectName(u"RxSwitch_Rec")
        self.RxSwitch_Rec.setEnabled(True)
        self.RxSwitch_Rec.setLayoutDirection(Qt.LayoutDirection.RightToLeft)

        self.verticalLayout_5.addWidget(self.RxSwitch_Rec)

        self.conn_amp_direct_25 = QFrame(self.centralwidget)
        self.conn_amp_direct_25.setObjectName(u"conn_amp_direct_25")
        self.conn_amp_direct_25.setEnabled(True)
        self.conn_amp_direct_25.setGeometry(QRect(80, 390, 21, 20))
        self.conn_amp_direct_25.setFrameShadow(QFrame.Shadow.Plain)
        self.conn_amp_direct_25.setLineWidth(2)
        self.conn_amp_direct_25.setFrameShape(QFrame.Shape.HLine)
        self.groupBox_34 = QGroupBox(self.centralwidget)
        self.groupBox_34.setObjectName(u"groupBox_34")
        self.groupBox_34.setGeometry(QRect(30, 377, 51, 31))
        self.groupBox_34.setFlat(False)
        self.groupBox_34.setCheckable(False)
        self.groupBox_35 = QGroupBox(self.centralwidget)
        self.groupBox_35.setObjectName(u"groupBox_35")
        self.groupBox_35.setGeometry(QRect(30, 407, 51, 31))
        self.groupBox_35.setFlat(False)
        self.groupBox_35.setCheckable(False)
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(440, 70, 161, 71))
        ReverbChamberRelaisController.setCentralWidget(self.centralwidget)
        self.conn_amp_direct_14.raise_()
        self.conn_amp_direct_15.raise_()
        self.conn_amp_direct_16.raise_()
        self.conn_amp_direct_13.raise_()
        self.conn_amp_lf.raise_()
        self.conn_amp_hf.raise_()
        self.conn_amp_direct.raise_()
        self.conn_amp_direct_2.raise_()
        self.conn_amp_direct_3.raise_()
        self.conn_amp_direct_4.raise_()
        self.conn_amp_direct_5.raise_()
        self.conn_amp_direct_6.raise_()
        self.conn_amp_direct_9.raise_()
        self.conn_amp_direct_10.raise_()
        self.conn_amp_direct_11.raise_()
        self.conn_amp_direct_12.raise_()
        self.conn_amp_direct_17.raise_()
        self.conn_amp_direct_18.raise_()
        self.conn_amp_direct_7.raise_()
        self.conn_amp_direct_8.raise_()
        self.conn_amp_direct_19.raise_()
        self.conn_amp_direct_20.raise_()
        self.conn_amp_direct_21.raise_()
        self.conn_amp_direct_22.raise_()
        self.conn_amp_direct_23.raise_()
        self.conn_amp_direct_25.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.groupBox_6.raise_()
        self.groupBox_8.raise_()
        self.groupBox_10.raise_()
        self.groupBox_11.raise_()
        self.groupBox_13.raise_()
        self.groupBox_15.raise_()
        self.groupBox_17.raise_()
        self.groupBox_18.raise_()
        self.groupBox_19.raise_()
        self.groupBox_20.raise_()
        self.groupBox_27.raise_()
        self.groupBox_31.raise_()
        self.groupBox_29.raise_()
        self.groupBox_30.raise_()
        self.groupBox_33.raise_()
        self.groupBox_34.raise_()
        self.groupBox_35.raise_()
        self.pushButton.raise_()
        self.statusbar = QStatusBar(ReverbChamberRelaisController)
        self.statusbar.setObjectName(u"statusbar")
        ReverbChamberRelaisController.setStatusBar(self.statusbar)

        self.retranslateUi(ReverbChamberRelaisController)
        self.sgSwitch_Direct.toggled.connect(self.conn_amp_direct.setEnabled)
        self.sgSwitch_HF.toggled.connect(self.conn_amp_hf.setEnabled)
        self.sgSwitch_LF.toggled.connect(self.conn_amp_lf.setEnabled)
        self.sgSwitch_HF.toggled.connect(self.conn_amp_direct_14.setEnabled)
        self.sgSwitch_HF.toggled.connect(self.conn_amp_direct_16.setEnabled)
        self.sgSwitch_LF.toggled.connect(self.conn_amp_direct_13.setEnabled)
        self.sgSwitch_LF.toggled.connect(self.conn_amp_direct_15.setEnabled)
        self.sgSwitch_LF.toggled.connect(self.conn_amp_direct_11.setEnabled)
        self.sgSwitch_LF.toggled.connect(self.conn_amp_direct_9.setEnabled)
        self.sgSwitch_HF.toggled.connect(self.conn_amp_direct_10.setEnabled)
        self.sgSwitch_HF.toggled.connect(self.conn_amp_direct_12.setEnabled)
        self.TxSwitch_Term.toggled.connect(self.conn_amp_direct_5.setEnabled)
        self.TxSwitch_HF.toggled.connect(self.conn_amp_direct_4.setEnabled)
        self.TxSwitch_LF.toggled.connect(self.conn_amp_direct_3.setEnabled)
        self.RxSwitch_LF.toggled.connect(self.conn_amp_direct_18.setEnabled)
        self.RxSwitch_HF.toggled.connect(self.conn_amp_direct_19.setEnabled)
        self.RxSwitch_PM.toggled.connect(self.conn_amp_direct_25.setEnabled)
        self.RxSwitch_Rec.toggled.connect(self.conn_amp_direct_23.setEnabled)
        self.pushButton.clicked.connect(self.TxSwitch_Term.click)
        self.pushButton.clicked.connect(self.sgSwitch_Direct.click)
        self.pushButton.clicked.connect(self.AttSwitch_On.click)
        self.sgSwitch_Direct.toggled.connect(self.conn_amp_direct_7.setDisabled)
        self.sgSwitch_Direct.toggled.connect(self.conn_amp_direct_8.setDisabled)
        self.sgSwitch_HF.toggled.connect(self.conn_amp_direct_7.setEnabled)
        self.sgSwitch_HF.toggled.connect(self.conn_amp_direct_8.setEnabled)
        self.sgSwitch_LF.toggled.connect(self.conn_amp_direct_7.setEnabled)
        self.sgSwitch_LF.toggled.connect(self.conn_amp_direct_8.setEnabled)

        QMetaObject.connectSlotsByName(ReverbChamberRelaisController)
    # setupUi

    def retranslateUi(self, ReverbChamberRelaisController):
        ReverbChamberRelaisController.setWindowTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Reverb Chamber Matrix Switch Controller ", None))
        self.groupBox.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Switch 1", None))
        self.sgSwitch_LF.setText(QCoreApplication.translate("ReverbChamberRelaisController", u"LF", None))
        self.sgSwitch_HF.setText(QCoreApplication.translate("ReverbChamberRelaisController", u"HF", None))
        self.sgSwitch_Direct.setText(QCoreApplication.translate("ReverbChamberRelaisController", u"Direct", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Amp LF", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Amp LF", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Amp LF", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Amp HF", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"DC LF", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Amp LF", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"DC HF", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Amp LF", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Switch 2", None))
        self.TxSwitch_LF.setText(QCoreApplication.translate("ReverbChamberRelaisController", u"LogPer", None))
        self.TxSwitch_HF.setText(QCoreApplication.translate("ReverbChamberRelaisController", u"Horn", None))
        self.TxSwitch_Term.setText(QCoreApplication.translate("ReverbChamberRelaisController", u"Term", None))
        self.groupBox_11.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"LogPer", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Amp LF", None))
        self.groupBox_23.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Term", None))
        self.groupBox_24.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Amp LF", None))
        self.groupBox_25.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Horn", None))
        self.groupBox_26.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Amp LF", None))
        self.groupBox_13.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Horn", None))
        self.groupBox_14.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Amp LF", None))
        self.groupBox_15.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Term", None))
        self.groupBox_16.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Amp LF", None))
        self.groupBox_17.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"SG", None))
        self.groupBox_18.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"PM FWD", None))
        self.groupBox_19.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"PM REV", None))
        self.groupBox_20.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Switch 3", None))
        self.RxSwitch_LF.setText(QCoreApplication.translate("ReverbChamberRelaisController", u"LogPer", None))
        self.RxSwitch_HF.setText(QCoreApplication.translate("ReverbChamberRelaisController", u"Horn", None))
        self.groupBox_27.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"LogPer", None))
        self.groupBox_28.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Amp LF", None))
        self.groupBox_31.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Horn", None))
        self.groupBox_32.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Amp LF", None))
        self.groupBox_29.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Switch 4", None))
        self.AttSwitch_On.setText(QCoreApplication.translate("ReverbChamberRelaisController", u"Att 20 dB", None))
        self.AttSwitch_Off.setText(QCoreApplication.translate("ReverbChamberRelaisController", u"direct", None))
        self.groupBox_30.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Att", None))
        self.groupBox_33.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Switch 5", None))
        self.RxSwitch_PM.setText(QCoreApplication.translate("ReverbChamberRelaisController", u"PM", None))
        self.RxSwitch_Rec.setText(QCoreApplication.translate("ReverbChamberRelaisController", u"Rec", None))
        self.groupBox_34.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"PM Rx", None))
        self.groupBox_35.setTitle(QCoreApplication.translate("ReverbChamberRelaisController", u"Rec", None))
        self.pushButton.setText(QCoreApplication.translate("ReverbChamberRelaisController", u"Safe Setting", None))
    # retranslateUi

